In [94]:
import pandas as pd
import numpy as np

In [95]:
df = pd.read_csv("smartphone.csv")
df

,model,price,rating,sim,processor,ram,battery,display,camera,card,os
0,OnePlus 11 5G,"₹54,999",89.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 8 Gen2, Octa Core, 3.2 GHz Processor","12 GB RAM, 256 GB inbuilt",5000 mAh Battery with 100W Fast Charging,"6.7 inches, 1440 x 3216 px, 120 Hz Display wit...",50 MP + 48 MP + 32 MP Triple Rear & 16 MP Fron...,Memory Card Not Supported,Android v13
1,OnePlus Nord CE 2 Lite 5G,"₹19,989",81.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi","Snapdragon 695, Octa Core, 2.2 GHz Processor","6 GB RAM, 128 GB inbuilt",5000 mAh Battery with 33W Fast Charging,"6.59 inches, 1080 x 2412 px, 120 Hz Display wi...",64 MP + 2 MP + 2 MP Triple Rear & 16 MP Front ...,"Memory Card (Hybrid), upto 1 TB",Android v12
2,Samsung Galaxy A14 5G,"₹16,499",75.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi","Exynos 1330, Octa Core, 2.4 GHz Processor","4 GB RAM, 64 GB inbuilt",5000 mAh Battery with 15W Fast Charging,"6.6 inches, 1080 x 2408 px, 90 Hz Display with...",50 MP + 2 MP + 2 MP Triple Rear & 13 MP Front ...,"Memory Card Supported, upto 1 TB",Android v13
3,Motorola Moto G62 5G,"₹14,999",81.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi","Snapdragon 695, Octa Core, 2.2 GHz Processor","6 GB RAM, 128 GB inbuilt",5000 mAh Battery with Fast Charging,"6.55 inches, 1080 x 2400 px, 120 Hz Display wi...",50 MP + 8 MP + 2 MP Triple Rear & 16 MP Front ...,"Memory Card (Hybrid), upto 1 TB",Android v12
4,Realme 10 Pro Plus,"₹24,999",82.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi","Dimensity 1080, Octa Core, 2.6 GHz Processor","6 GB RAM, 128 GB inbuilt",5000 mAh Battery with 67W Fast Charging,"6.7 inches, 1080 x 2412 px, 120 Hz Display wit...",108 MP + 8 MP + 2 MP Triple Rear & 16 MP Front...,Memory Card Not Supported,Android v13
...,...,...,...,...,...,...,...,...,...,...,...
1015,Motorola Moto Edge S30 Pro,"₹34,990",83.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi","Snapdragon 8 Gen1, Octa Core, 3 GHz Processor","8 GB RAM, 128 GB inbuilt",5000 mAh Battery with 68.2W Fast Charging,"6.67 inches, 1080 x 2460 px, 120 Hz Display wi...",64 MP + 8 MP + 2 MP Triple Rear & 16 MP Front ...,Android v12,No FM Radio
1016,Honor X8 5G,"₹14,990",75.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi","Snapdragon 480+, Octa Core, 2.2 GHz Processor","6 GB RAM, 128 GB inbuilt",5000 mAh Battery with 22.5W Fast Charging,"6.5 inches, 720 x 1600 px Display with Water D...",48 MP + 2 MP + Depth Sensor Triple Rear & 8 MP...,"Memory Card Supported, upto 1 TB",Android v11
1017,POCO X4 GT 5G (8GB RAM + 256GB),"₹28,990",85.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC, IR Bl...","Dimensity 8100, Octa Core, 2.85 GHz Processor","8 GB RAM, 256 GB inbuilt",5080 mAh Battery with 67W Fast Charging,"6.6 inches, 1080 x 2460 px, 144 Hz Display wit...",64 MP + 8 MP + 2 MP Triple Rear & 16 MP Front ...,Memory Card Not Supported,Android v12
1018,Motorola Moto G91 5G,"₹19,990",80.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 695, Octa Core, 2.2 GHz Processor","6 GB RAM, 128 GB inbuilt",5000 mAh Battery with Fast Charging,"6.8 inches, 1080 x 2400 px Display with Punch ...",108 MP + 8 MP + 2 MP Triple Rear & 32 MP Front...,"Memory Card Supported, upto 1 TB",Android v12
1019,Samsung Galaxy M52s 5G,"₹24,990",74.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi",Octa Core Processor,"8 GB RAM, 128 GB inbuilt",5000 mAh Battery with Fast Charging,"6.5 inches, 1080 x 2400 px Display with Water ...",64 MP + 8 MP + 5 MP Triple Rear & 32 MP Front ...,"Memory Card Supported, upto 1 TB",Android v12

In [96]:
# clean
# null values 
# outliers
# data quality
#  syntax
# cloumn value mismatch
# data type relatde problame
# not avelable
# tidiness issue
# seperate colume thire crsprang values

In [97]:
df["price"]

0       ₹54,999
1       ₹19,989
2       ₹16,499
3       ₹14,999
4       ₹24,999
         ...
1015    ₹34,990
1016    ₹14,990
1017    ₹28,990
1018    ₹19,990
1019    ₹24,990
Name: price, Length: 1020, dtype: object

In [98]:
# convert cat/ str numaric

In [99]:
for i in df["price"]:
    print(int(i.replace("₹" , "").replace("," , "")))

54999
19989
16499
14999
24999
16999
65999
29999
26749
28999
18999
18999
24762
16990
114990
62999
9999
45999
32999
14499
39999
35999
14999
17859
42990
31239
21995
129990
27999
69999
19999
20999
27990
38999
23790
39999
29990
91999
32999
28499
21999
19999
18999
27999
18499
17478
11936
8950
12489
42999
18999
29999
11990
18999
13999
14965
74999
10999
84990
10499
17990
29990
18499
16499
14999
35499
60999
32999
15999
99990
9499
27994
13989
44999
13999
6190
119900
27660
24999
8388
15999
20999
13999
19990
13999
22999
22999
16999
14290
41999
13489
22990
16499
73999
9999
12499
12499
59999
106990
15990
119990
19999
23990
12999
19990
58990
43999
49999
15999
36999
39999
51999
22999
31999
6171
29340
25289
21788
69999
70990
34999
33900
29999
18999
19499
24994
10999
24999
25999
34990
13466
9999
7999
28249
16499
22999
46999
13999
13490
28999
15499
39999
12999
4499
14999
8499
24990
16999
9589
40999
19988
11999
142990
30990
19499
4990
5299
25969
28999
94990
14999
14999
129900
58990
41990
10999
11999
16999
30990
17999
5499
20499
20490
15490
29990
15499
11999
10999
21990
31999
11999
36999
6999
39999
14999
14499
27999
20499
8099
10999
3499
9990
34999
46999
39999
11828
45999
18999
17999
8499
17999
14450
54999
71999
12999
11499
35999
34999
11999
27994
139990
39999
15499
18999
10999
27999
81999
9999
31994
9299
29990
25900
16999
24999
12188
8999
7499
17999
24999
45999
65499
58990
11999
11999
18990
14499
106990
10499
26990
19990
24999
13969
44999
24999
53100
16999
21899
75999
25999
46990
9999
49999
17999
16940
17990
20990
51999
64449
8990
19999
13499
15499
6499
71999
36499
15999
31994
34999
18999
39990
16499
6199
54300
9999
15990
22700
50990
64900
13799
8999
89999
21994
69990
12999
24990
19990
26999
19999
16900
19999
182999
12999
15999
13999
7749
24999
59999
25895
46990
7499
7790
25999
6299
12999
11999
21890
69999
55999
55999
14999
25994
42999
33499
118999
16999
6990
29990
12944
29990
16999
64999
154998
109999
84999
27499
8999
40480
17999
105999
8999
14999
19990
23399
41990
22998
25999
11700
6499
15999
64800
14590
7499
21999
11999
12999
20990
72999
77990
56999
21999
9499
7499
4649
18000
38999
7145
14990
15499
9999
29999
15999
59990
34990
45999
119990
89990
50999
7999
43999
18499
134999
32999
13499
35489
20120
42999
4649
24999
20999
28994
48900
22494
8990
6999
8890
18498
23999
22994
12990
14999
18499
14990
70990
12120
29990
20999
11999
17990
14990
6490
2999
34999
149900
6499
104999
13999
16999
79999
36760
23499
75990
21990
18999
7249
16990
23890
26380
27999
10850
19999
129990
19990
41990
69990
39990
74999
36994
14700
34990
34999
13990
650000
14859
17999
34990
14990
8999
8999
15824
43900
22494
19650
6999
16499
15999
72999
26999
6999
130990
12787
9999
54999
15490
25999
9499
7999
63990
15990
34949
8799
12390
11499
199990
42990
34999
11999
10499
8910
24990
17999
22999
6490
21990
1762
12364
39990
11999
7499
3990
10499
6299
5990
113990
239999
21999
15999
6899
69990
12990
92980
15999
23999
12999
60990
8859
33749
15990
24990
14999
17990
24990
11600
8299
11999
89999
27999
15990
7289
30990
15499
8499
14490
15490
14990
15999
36000
69999
26990
10630
42990
24990
14489
16490
24494
7999
23990
49959
129900
19990
14990
23269
13999
1949
2799
35389
79700
9499
12340
10799
14990
61990
51880
16990
19990
57999
46990
20990
17990
17499
17999
49990
2399
14999
19980
35990
15999
41999
25999
7990
29990
27990
29999
8999
13999
11499
39999
27999
24499
60999
110999
54999
16490
24990
1299
25000
1999
9950
12999
19999
32999
28498
15998
3749
59990
16990
27999
13499
16499
10999
13990
9999
31994
24820
22990
59990
8999
10499
7499
9990
12490
13990
17990
24999
21999
19999
99999
109900
52990
99
19990
11499
699
13999
22990
28990
27999
19990
22999
17999
15499
17990
13999
13499
14799
6999
11999
23994
3589
139900
69999
57999
86000
11999
14999
26499
8990
95999
47990
17990
22999
1299
99990
39999
38999
12490
5490
39990
1339
16685
69990
6999
71999
26999
16499
17990
8999
39900
2799
5999
34999
16990
22990
19990
10850
13499
958
6699
17999
13990
94990
8968
7320
8999
13999
14746
16999
25990
16499
19999
23500
54999
19499
79990
39999
92999
1799
32990
14499
13999
7999
5785
12990
19990
23990
17999
16999
9999
8299
82199
1850
49990
11999
29990
92249
139900
14990
15988
11725
17994
134999
25595
7499
10890
18990
19990
15990
58999
12500
29999
31990
29999
107990
31990
48990
99990
9499
162990
24999
82990
15999
8999
17990
82990
12999
29990
6999
60999
27990
5249
14999
44990
22490
50990
11499
5990
27000
29999
27990
3290
74999
9990
19990
13279
11000
18900
12999
7299
995
7999
54990
49990
54990
49990
15499
169900
53990
18990
16999
34999
82990
46999
8499
16999
11499
88999
15990
24990
79990
6249
12499
6499
179900
11990
26990
13499
75999
5999
8499
11990
10990
109990
16999
12199
11490
5490
11499
59450
12799
83000
14490
82990
9490
25000
15000
20990
34999
29999
11999
12999
124990
28999
12999
28499
104999
172999
17990
13774
2239
8999
18990
14999
7999
39999
11990
12999
54999
24990
59999
19999
16999
14999
29990
13990
17999
11399
599
19990
15499
6999
12499
91999
9690
32990
42990
14999
18699
1749
10990
30990
59999
23999
9999
3099
119900
9299
12989
4999
11999
29990
12490
27999
8199
21990
20000
11990
11989
11490
11490
15999
17990
78990
10949
10300
1899
45999
21990
19990
32990
14499
41990
13990
1599
4799
10490
29990
22990
47990
19999
29999
11879
28990
39990
15999
22990
149999
11499
22999
7999
31999
30990
7999
10999
14990
14499
44999
17999
19999
3999
101999
38700
19999
10999
16990
55999
67999
9999
14439
2499
9990
24999
85990
480000
16999
8999
15990
3999
3890
1685
84990
21999
2099
8999
649
20999
32990
9022
8399
9999
8390
19999
13999
29999
8990
163980
24990
59990
47990
40990
22999
12990
14999
42999
14999
22990
118990
29990
7399
17999
12799
26999
22999
147900
44999
7790
39990
9999
22990
32999
32990
14999
12499
39990
6499
18499
30994
32999
10499
19999
17499
10990
19000
13990
10499
5890
6490
54999
9990
24999
3399
59990
214990
9990
6999
169000
39990
21490
13490
7999
8990
13999
1999
13990
14999
6999
42990
6799
25899
54999
49990
32990
8720
69990
4787
70990
119990
34990
14990
28990
19990
24990

In [100]:
df["price"]

0       ₹54,999
1       ₹19,989
2       ₹16,499
3       ₹14,999
4       ₹24,999
         ...
1015    ₹34,990
1016    ₹14,990
1017    ₹28,990
1018    ₹19,990
1019    ₹24,990
Name: price, Length: 1020, dtype: object

In [101]:
#for i in df.index:
#    df["price"][i] = int(df["price"][i].replace("₹" , " ").replace("," , ""))

In [102]:
df["price"]

0       ₹54,999
1       ₹19,989
2       ₹16,499
3       ₹14,999
4       ₹24,999
         ...
1015    ₹34,990
1016    ₹14,990
1017    ₹28,990
1018    ₹19,990
1019    ₹24,990
Name: price, Length: 1020, dtype: object

In [103]:
df["price"] = df["price"].str.replace("₹" , "").str.replace("," ,"").astype(int)

In [104]:
df.head()

,model,price,rating,sim,processor,ram,battery,display,camera,card,os
0,OnePlus 11 5G,54999,89.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 8 Gen2, Octa Core, 3.2 GHz Processor","12 GB RAM, 256 GB inbuilt",5000 mAh Battery with 100W Fast Charging,"6.7 inches, 1440 x 3216 px, 120 Hz Display wit...",50 MP + 48 MP + 32 MP Triple Rear & 16 MP Fron...,Memory Card Not Supported,Android v13
1,OnePlus Nord CE 2 Lite 5G,19989,81.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi","Snapdragon 695, Octa Core, 2.2 GHz Processor","6 GB RAM, 128 GB inbuilt",5000 mAh Battery with 33W Fast Charging,"6.59 inches, 1080 x 2412 px, 120 Hz Display wi...",64 MP + 2 MP + 2 MP Triple Rear & 16 MP Front ...,"Memory Card (Hybrid), upto 1 TB",Android v12
2,Samsung Galaxy A14 5G,16499,75.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi","Exynos 1330, Octa Core, 2.4 GHz Processor","4 GB RAM, 64 GB inbuilt",5000 mAh Battery with 15W Fast Charging,"6.6 inches, 1080 x 2408 px, 90 Hz Display with...",50 MP + 2 MP + 2 MP Triple Rear & 13 MP Front ...,"Memory Card Supported, upto 1 TB",Android v13
3,Motorola Moto G62 5G,14999,81.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi","Snapdragon 695, Octa Core, 2.2 GHz Processor","6 GB RAM, 128 GB inbuilt",5000 mAh Battery with Fast Charging,"6.55 inches, 1080 x 2400 px, 120 Hz Display wi...",50 MP + 8 MP + 2 MP Triple Rear & 16 MP Front ...,"Memory Card (Hybrid), upto 1 TB",Android v12
4,Realme 10 Pro Plus,24999,82.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi","Dimensity 1080, Octa Core, 2.6 GHz Processor","6 GB RAM, 128 GB inbuilt",5000 mAh Battery with 67W Fast Charging,"6.7 inches, 1080 x 2412 px, 120 Hz Display wit...",108 MP + 8 MP + 2 MP Triple Rear & 16 MP Front...,Memory Card Not Supported,Android v13

In [105]:
df

,model,price,rating,sim,processor,ram,battery,display,camera,card,os
0,OnePlus 11 5G,54999,89.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 8 Gen2, Octa Core, 3.2 GHz Processor","12 GB RAM, 256 GB inbuilt",5000 mAh Battery with 100W Fast Charging,"6.7 inches, 1440 x 3216 px, 120 Hz Display wit...",50 MP + 48 MP + 32 MP Triple Rear & 16 MP Fron...,Memory Card Not Supported,Android v13
1,OnePlus Nord CE 2 Lite 5G,19989,81.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi","Snapdragon 695, Octa Core, 2.2 GHz Processor","6 GB RAM, 128 GB inbuilt",5000 mAh Battery with 33W Fast Charging,"6.59 inches, 1080 x 2412 px, 120 Hz Display wi...",64 MP + 2 MP + 2 MP Triple Rear & 16 MP Front ...,"Memory Card (Hybrid), upto 1 TB",Android v12
2,Samsung Galaxy A14 5G,16499,75.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi","Exynos 1330, Octa Core, 2.4 GHz Processor","4 GB RAM, 64 GB inbuilt",5000 mAh Battery with 15W Fast Charging,"6.6 inches, 1080 x 2408 px, 90 Hz Display with...",50 MP + 2 MP + 2 MP Triple Rear & 13 MP Front ...,"Memory Card Supported, upto 1 TB",Android v13
3,Motorola Moto G62 5G,14999,81.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi","Snapdragon 695, Octa Core, 2.2 GHz Processor","6 GB RAM, 128 GB inbuilt",5000 mAh Battery with Fast Charging,"6.55 inches, 1080 x 2400 px, 120 Hz Display wi...",50 MP + 8 MP + 2 MP Triple Rear & 16 MP Front ...,"Memory Card (Hybrid), upto 1 TB",Android v12
4,Realme 10 Pro Plus,24999,82.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi","Dimensity 1080, Octa Core, 2.6 GHz Processor","6 GB RAM, 128 GB inbuilt",5000 mAh Battery with 67W Fast Charging,"6.7 inches, 1080 x 2412 px, 120 Hz Display wit...",108 MP + 8 MP + 2 MP Triple Rear & 16 MP Front...,Memory Card Not Supported,Android v13
...,...,...,...,...,...,...,...,...,...,...,...
1015,Motorola Moto Edge S30 Pro,34990,83.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi","Snapdragon 8 Gen1, Octa Core, 3 GHz Processor","8 GB RAM, 128 GB inbuilt",5000 mAh Battery with 68.2W Fast Charging,"6.67 inches, 1080 x 2460 px, 120 Hz Display wi...",64 MP + 8 MP + 2 MP Triple Rear & 16 MP Front ...,Android v12,No FM Radio
1016,Honor X8 5G,14990,75.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi","Snapdragon 480+, Octa Core, 2.2 GHz Processor","6 GB RAM, 128 GB inbuilt",5000 mAh Battery with 22.5W Fast Charging,"6.5 inches, 720 x 1600 px Display with Water D...",48 MP + 2 MP + Depth Sensor Triple Rear & 8 MP...,"Memory Card Supported, upto 1 TB",Android v11
1017,POCO X4 GT 5G (8GB RAM + 256GB),28990,85.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC, IR Bl...","Dimensity 8100, Octa Core, 2.85 GHz Processor","8 GB RAM, 256 GB inbuilt",5080 mAh Battery with 67W Fast Charging,"6.6 inches, 1080 x 2460 px, 144 Hz Display wit...",64 MP + 8 MP + 2 MP Triple Rear & 16 MP Front ...,Memory Card Not Supported,Android v12
1018,Motorola Moto G91 5G,19990,80.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 695, Octa Core, 2.2 GHz Processor","6 GB RAM, 128 GB inbuilt",5000 mAh Battery with Fast Charging,"6.8 inches, 1080 x 2400 px Display with Punch ...",108 MP + 8 MP + 2 MP Triple Rear & 32 MP Front...,"Memory Card Supported, upto 1 TB",Android v12
1019,Samsung Galaxy M52s 5G,24990,74.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi",Octa Core Processor,"8 GB RAM, 128 GB inbuilt",5000 mAh Battery with Fast Charging,"6.5 inches, 1080 x 2400 px Display with Water ...",64 MP + 8 MP + 5 MP Triple Rear & 32 MP Front ...,"Memory Card Supported, upto 1 TB",Android v12

In [106]:
df1 =  df.copy()

In [107]:
df1.head()

,model,price,rating,sim,processor,ram,battery,display,camera,card,os
0,OnePlus 11 5G,54999,89.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 8 Gen2, Octa Core, 3.2 GHz Processor","12 GB RAM, 256 GB inbuilt",5000 mAh Battery with 100W Fast Charging,"6.7 inches, 1440 x 3216 px, 120 Hz Display wit...",50 MP + 48 MP + 32 MP Triple Rear & 16 MP Fron...,Memory Card Not Supported,Android v13
1,OnePlus Nord CE 2 Lite 5G,19989,81.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi","Snapdragon 695, Octa Core, 2.2 GHz Processor","6 GB RAM, 128 GB inbuilt",5000 mAh Battery with 33W Fast Charging,"6.59 inches, 1080 x 2412 px, 120 Hz Display wi...",64 MP + 2 MP + 2 MP Triple Rear & 16 MP Front ...,"Memory Card (Hybrid), upto 1 TB",Android v12
2,Samsung Galaxy A14 5G,16499,75.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi","Exynos 1330, Octa Core, 2.4 GHz Processor","4 GB RAM, 64 GB inbuilt",5000 mAh Battery with 15W Fast Charging,"6.6 inches, 1080 x 2408 px, 90 Hz Display with...",50 MP + 2 MP + 2 MP Triple Rear & 13 MP Front ...,"Memory Card Supported, upto 1 TB",Android v13
3,Motorola Moto G62 5G,14999,81.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi","Snapdragon 695, Octa Core, 2.2 GHz Processor","6 GB RAM, 128 GB inbuilt",5000 mAh Battery with Fast Charging,"6.55 inches, 1080 x 2400 px, 120 Hz Display wi...",50 MP + 8 MP + 2 MP Triple Rear & 16 MP Front ...,"Memory Card (Hybrid), upto 1 TB",Android v12
4,Realme 10 Pro Plus,24999,82.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi","Dimensity 1080, Octa Core, 2.6 GHz Processor","6 GB RAM, 128 GB inbuilt",5000 mAh Battery with 67W Fast Charging,"6.7 inches, 1080 x 2412 px, 120 Hz Display wit...",108 MP + 8 MP + 2 MP Triple Rear & 16 MP Front...,Memory Card Not Supported,Android v13

In [108]:
df1

,model,price,rating,sim,processor,ram,battery,display,camera,card,os
0,OnePlus 11 5G,54999,89.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 8 Gen2, Octa Core, 3.2 GHz Processor","12 GB RAM, 256 GB inbuilt",5000 mAh Battery with 100W Fast Charging,"6.7 inches, 1440 x 3216 px, 120 Hz Display wit...",50 MP + 48 MP + 32 MP Triple Rear & 16 MP Fron...,Memory Card Not Supported,Android v13
1,OnePlus Nord CE 2 Lite 5G,19989,81.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi","Snapdragon 695, Octa Core, 2.2 GHz Processor","6 GB RAM, 128 GB inbuilt",5000 mAh Battery with 33W Fast Charging,"6.59 inches, 1080 x 2412 px, 120 Hz Display wi...",64 MP + 2 MP + 2 MP Triple Rear & 16 MP Front ...,"Memory Card (Hybrid), upto 1 TB",Android v12
2,Samsung Galaxy A14 5G,16499,75.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi","Exynos 1330, Octa Core, 2.4 GHz Processor","4 GB RAM, 64 GB inbuilt",5000 mAh Battery with 15W Fast Charging,"6.6 inches, 1080 x 2408 px, 90 Hz Display with...",50 MP + 2 MP + 2 MP Triple Rear & 13 MP Front ...,"Memory Card Supported, upto 1 TB",Android v13
3,Motorola Moto G62 5G,14999,81.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi","Snapdragon 695, Octa Core, 2.2 GHz Processor","6 GB RAM, 128 GB inbuilt",5000 mAh Battery with Fast Charging,"6.55 inches, 1080 x 2400 px, 120 Hz Display wi...",50 MP + 8 MP + 2 MP Triple Rear & 16 MP Front ...,"Memory Card (Hybrid), upto 1 TB",Android v12
4,Realme 10 Pro Plus,24999,82.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi","Dimensity 1080, Octa Core, 2.6 GHz Processor","6 GB RAM, 128 GB inbuilt",5000 mAh Battery with 67W Fast Charging,"6.7 inches, 1080 x 2412 px, 120 Hz Display wit...",108 MP + 8 MP + 2 MP Triple Rear & 16 MP Front...,Memory Card Not Supported,Android v13
...,...,...,...,...,...,...,...,...,...,...,...
1015,Motorola Moto Edge S30 Pro,34990,83.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi","Snapdragon 8 Gen1, Octa Core, 3 GHz Processor","8 GB RAM, 128 GB inbuilt",5000 mAh Battery with 68.2W Fast Charging,"6.67 inches, 1080 x 2460 px, 120 Hz Display wi...",64 MP + 8 MP + 2 MP Triple Rear & 16 MP Front ...,Android v12,No FM Radio
1016,Honor X8 5G,14990,75.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi","Snapdragon 480+, Octa Core, 2.2 GHz Processor","6 GB RAM, 128 GB inbuilt",5000 mAh Battery with 22.5W Fast Charging,"6.5 inches, 720 x 1600 px Display with Water D...",48 MP + 2 MP + Depth Sensor Triple Rear & 8 MP...,"Memory Card Supported, upto 1 TB",Android v11
1017,POCO X4 GT 5G (8GB RAM + 256GB),28990,85.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC, IR Bl...","Dimensity 8100, Octa Core, 2.85 GHz Processor","8 GB RAM, 256 GB inbuilt",5080 mAh Battery with 67W Fast Charging,"6.6 inches, 1080 x 2460 px, 144 Hz Display wit...",64 MP + 8 MP + 2 MP Triple Rear & 16 MP Front ...,Memory Card Not Supported,Android v12
1018,Motorola Moto G91 5G,19990,80.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 695, Octa Core, 2.2 GHz Processor","6 GB RAM, 128 GB inbuilt",5000 mAh Battery with Fast Charging,"6.8 inches, 1080 x 2400 px Display with Punch ...",108 MP + 8 MP + 2 MP Triple Rear & 32 MP Front...,"Memory Card Supported, upto 1 TB",Android v12
1019,Samsung Galaxy M52s 5G,24990,74.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi",Octa Core Processor,"8 GB RAM, 128 GB inbuilt",5000 mAh Battery with Fast Charging,"6.5 inches, 1080 x 2400 px Display with Water ...",64 MP + 8 MP + 5 MP Triple Rear & 32 MP Front ...,"Memory Card Supported, upto 1 TB",Android v12

In [109]:
df["processor"]

0       Snapdragon 8 Gen2, Octa Core, 3.2 GHz Processor
1          Snapdragon 695, Octa Core, 2.2 GHz Processor
2             Exynos 1330, Octa Core, 2.4 GHz Processor
3         Snapdragon  695, Octa Core, 2.2 GHz Processor
4          Dimensity 1080, Octa Core, 2.6 GHz Processor
                             ...
1015      Snapdragon 8 Gen1, Octa Core, 3 GHz Processor
1016     Snapdragon  480+, Octa Core, 2.2 GHz Processor
1017      Dimensity 8100, Octa Core, 2.85 GHz Processor
1018       Snapdragon 695, Octa Core, 2.2 GHz Processor
1019                                Octa Core Processor
Name: processor, Length: 1020, dtype: object

In [110]:
for i in df["processor"]:
    if "processor" not in i:
        print(i)

Snapdragon 8 Gen2, Octa Core, 3.2 GHz Processor
Snapdragon 695, Octa Core, 2.2 GHz Processor
Exynos 1330, Octa Core, 2.4 GHz Processor
Snapdragon  695, Octa Core, 2.2 GHz Processor
Dimensity 1080, Octa Core, 2.6 GHz Processor
Snapdragon  750G, Octa Core, 2.2 GHz Processor
Bionic A15, Hexa Core, 3.22 GHz Processor
Dimensity 1080, Octa Core, 2.6 GHz Processor
Snapdragon 778G Plus, Octa Core, 2.5 GHz Processor
Dimensity  1300, Octa Core, 3 GHz Processor
Snapdragon 695, Octa Core, 2.2 GHz Processor
Dimensity 700 5G, Octa Core, 2.2 GHz Processor
Dimensity 1080, Octa Core, 2.6 GHz Processor
Snapdragon  695, Octa Core, 2.2 GHz Processor
Snapdragon 8 Gen2, Octa Core, 3.2 GHz Processor
Bionic A15, Hexa Core, 3.22 GHz Processor
Helio P35, Octa Core, 2.3 GHz Processor
Snapdragon 8+ Gen1, Octa Core, 3.2 GHz Processor
Dimensity 8100 Max, Octa Core, 2.85 GHz Processor
Helio G70, Octa Core, 2 GHz Processor
Snapdragon  8+ Gen1, Octa Core, 3.2 GHz Processor
Dimensity 1300, Octa Core, 3 GHz Processor
Snapdragon 695 , Octa Core, 2.2 GHz Processor
Snapdragon 4 Gen 1, Octa Core, 2 GHz Processor
Dimensity 9000 Plus, Octa Core, 3.2 GHz Processor
Snapdragon 865, Octa Core, 2.84 GHz Processor
Snapdragon 695, Octa Core, 2.2 GHz Processor
Bionic  A16, Hexa Core Processor
Dimensity  900, Octa Core, 2 GHz Processor
Snapdragon  8 Gen2, Octa Core, 3.2 GHz Processor
Snapdragon 695, Octa Core, 2.2 GHz Processor
Snapdragon 778G, Octa Core, 2.4 GHz Processor
Dimensity  930, Octa Core, 2.2 GHz Processor
A13 Bionic, Hexa Core, 2.65 GHz Processor
Dimensity  900 5G, Octa Core, 2.4 GHz Processor
Exynos  2100, Octa Core, 2.9 GHz Processor
Snapdragon  695, Octa Core, 2.2 GHz Processor
Snapdragon  8 Gen1, Octa Core, 3 GHz Processor
Snapdragon  7 Gen1, Octa Core, 2.36 GHz Processor
Snapdragon 778G, Octa Core, 2.4 GHz Processor
Snapdragon  695, Octa Core, 2.2 GHz Processor
 Snapdragon  695, Octa Core, 2.2 GHz Processor
Dimensity 800U, Octa Core, 2.4 GHz Processor
Dimensity 1080, Octa Core, 2.6 GHz Processor
Snapdragon 680, Octa Core, 2.4 GHz Processor
Exynos  1280, Octa Core, 2.4 GHz Processor
Snapdragon  680, Octa Core, 2.4 GHz Processor
Unisoc T612, Octa Core, 1.8 GHz Processor
Helio P35, Octa Core, 2.3 GHz Processor
Snapdragon 7 Gen1, Octa Core, 2.36 GHz Processor
Exynos 1330, Octa Core, 2.4 GHz Processor
Dimensity 8200, Octa Core, 3.1 GHz Processor
Snapdragon 480+, Octa Core, 2.2 GHz Processor
Snapdragon 695, Octa Core, 2.2 GHz Processor
Helio G99, Octa Core, 2.2 GHz Processor
Dimensity 810 5G, Octa Core, 2.4 GHz Processor
Bionic A15, Hexa Core, 3.22 GHz Processor
Helio G95, Octa Core, 2.05 GHz Processor
Snapdragon 8 Gen2, Octa Core, 3.2 GHz Processor
Snapdragon 680, Octa Core, 2.4 GHz Processor
Dimensity 720, Octa Core, 2 GHz Processor
Snapdragon 870, Octa Core, 3.2 GHz Processor
Snapdragon  680, Octa Core, 2.4 GHz Processor
Helio G70, Octa Core, 2 GHz Processor
Dimensity  810 5G, Octa Core, 2.4 GHz Processor
Dimensity 8200, Octa Core, 3.1 GHz Processor
Snapdragon  8 Gen1, Octa Core, 3 GHz Processor
Dimensity 1080, Octa Core, 2.6 GHz Processor
Snapdragon  750G, Octa Core, 2.2 GHz Processor
Snapdragon  8+ Gen1, Octa Core, 3.2 GHz Processor
Helio G35, Octa Core, 2.3 GHz Processor
Dimensity  920 5G, Octa Core, 2.5 GHz Processor
Snapdragon  4 Gen 1, Octa Core, 2 GHz Processor
Snapdragon 8+ Gen1, Octa Core, 3.2 GHz Processor
Dimensity 700 , Octa Core, 2.2 GHz Processor
Tiger  T310, Quad Core, 2 GHz Processor
Bionic A15, Hexa Core, 3.22 GHz Processor
Snapdragon 6 Gen 1, Octa Core, 2.2 GHz Processor
Exynos 1280, Octa Core Processor
Helio  G25, Octa Core, 2 GHz Processor
Helio  G99, Octa Core, 2.2 GHz Processor
Exynos 1330, Octa Core, 2.4 GHz Processor
Dimensity  810 5G, Octa Core, 2.4 GHz Processor
Snapdragon  695, Octa Core, 2.2 GHz Processor
Dimensity 700, Octa Core, 2.2 GHz Processor
Snapdragon 778G+, Octa Core, 2.5 GHz Processor
Snapdragon 695, Octa Core, 2.2 GHz Processor
Dimensity  810 5G, Octa Core, 2.4 GHz Processor
Snapdragon  680, Octa Core, 2.4 GHz Processor
Snapdragon 778G, Octa Core, 2.4 GHz Processor
Helio P35, Octa Core, 2.3 GHz Processor
Dimensity 8100 Max, Octa Core, 2.85 GHz Processor
Snapdragon  695, Octa Core, 2.2 GHz Processor
Snapdragon 8 Gen2, Octa Core, 3.2 GHz Processor
Unisoc T612, Octa Core, 1.8 GHz Processor
Snapdragon  680, Octa Core, 2.4 GHz Processor
Helio G35, Octa Core, 2.3 GHz Processor
Snapdragon 8 Gen2, Octa Core, 3.2 GHz Processor
Snapdragon 8 Gen1, Octa Core, 3 GHz Processor
Snapdragon  695, Octa Core, 2.2 GHz Processor
Bionic  A16, Hexa Core Processor
Snapdragon 778G, Octa Core, 2.4 GHz Processor
Snapdragon 888+, Octa Core, 2.9 GHz Processor
Dimensity 810 5G, Octa Core, 2.4 GHz Processor
Dimensity 800U , Octa Core, 2.4 GHz Processor
Snapdragon 8 Gen2, Octa Core, 3.2 GHz Processor
Dimensity 9000 Plus, Octa Core, 3.2 GHz Processor
Snapdragon  8 Gen1, Octa Core, 3 GHz Processor
Snapdragon 680, Octa Core, 2.4 GHz Processor
Dimensity 8100 Max, Octa Core, 2.85 GHz Processor
Dimensity 9000, Octa Core, 3.05 GHz Processor
Bionic A14, Hexa Core, 3.1 GHz Processor
Dimensity  8100, Octa Core, 2.85 GHz Processor
Exynos 1280, Octa Core, 2.4 GHz Processor
Helio A22, Quad Core, 2 GHz Processor
Dimensity 1300, Octa Core, 3 GHz Processor
Dimensity  900 5G, Octa Core, 2.4 GHz Processor
Snapdragon  778G, Octa Core, 2.4 GHz Processor
Octa Core Processor
Snapdragon 8 Gen2, Octa Core, 3.2 GHz Processor
Snapdragon 8 Gen1, Octa Core, 3 GHz Processor
Dimensity  1300, Octa Core, 3 GHz Processor
Google  Tensor, Octa Core Processor
Dimensity 810 5G, Octa Core, 2.4 GHz Processor
Exynos  1280, Octa Core, 2.4 GHz Processor
Dimensity  920 5G, Octa Core, 2.5 GHz Processor
Snapdragon 680, Octa Core, 2.4 GHz Processor
Snapdragon 695, Octa Core, 2.2 GHz Processor
Exynos  1280, Octa Core, 2.4 GHz Processor
Google  Tensor, Octa Core Processor
Dimensity 700 5G, Octa Core, 2.2 GHz Processor
Snapdragon 720G, Octa Core, 2.3 GHz Processor
Tiger T700, Octa Core, 1.8 GHz Processor
Snapdragon 778G Plus, Octa Core, 2.5 GHz Processor
Snapdragon 695 , Octa Core, 2.2 GHz Processor
 Snapdragon  695, Octa Core, 2.2 GHz Processor
A13 Bionic, Hexa Core, 2.65 GHz Processor
Tiger  T616, Octa Core, 1.8 GHz Processor
Snapdragon 680, Octa Core, 2.4 GHz Processor
Snapdragon 870, Octa Core, 3.2 GHz Processor
Snapdragon  695 , Octa Core, 2.2 GHz Processor
Dimensity 8100 Max, Octa Core, 2.85 GHz Processor
Dimensity  810 5G, Octa Core, 2.4 GHz Processor
Quad Core, 1.4 GHz Processor
Snapdragon 460 , Octa Core, 1.8 GHz Processor
Helio P35, Octa Core, 2.3 GHz Processor
Snapdragon 870, Octa Core, 3.2 GHz Processor
Exynos 1200, Octa Core, 2.4 GHz Processor
Snapdragon 680, Octa Core, 2.4 GHz Processor
Bionic A14, Hexa Core, 3.1 GHz Processor
Snapdragon 4 Gen 1, Octa Core, 2 GHz Processor
Snapdragon 680, Octa Core, 2.4 GHz Processor
Bionic  A16
Snapdragon 8 Gen1, Octa Core, 3 GHz Processor
Dimensity 1080, Octa Core, 2.6 GHz Processor
Snapdragon QM215, Quad Core, 1.3 GHz Processor
Tiger T612, Octa Core, 1.82 GHz Processor
 Snapdragon 695, Octa Core, 2.2 GHz Processor
Snapdragon  8 Gen1, Octa Core, 3 GHz Processor
Snapdragon 8+ Gen1, Octa Core, 3.2 GHz Processor
Snapdragon 680, Octa Core, 2.4 GHz Processor
Helio G99, Octa Core, 2.2 GHz Processor
Bionic A15, Hexa Core, 3.22 GHz Processor
Snapdragon 8 Gen2, Octa Core, 3.2 GHz Processor
Dimensity 9200, Octa Core, 3.05 GHz Processor
Exynos 850, Octa Core, 2 GHz Processor
Helio G95, Octa Core, 2.05 GHz Processor
Helio G99, Octa Core, 2.2 GHz Processor
Snapdragon  888 , Octa Core, 2.84 GHz Processor
Dimensity 810, Octa Core, 2.4 GHz Processor
Tiger T310, Quad Core, 2 GHz Processor
Snapdragon  7 Gen1, Octa Core, 2.36 GHz Processor
Dimensity  920 5G, Octa Core, 2.5 GHz Processor
Snapdragon  480 , Octa Core, 2 GHz Processor
A13 Bionic, Hexa Core, 2.65 GHz Processor
Snapdragon  4 Gen 1, Octa Core, 2 GHz Processor
Helio G95, Octa Core, 2.05 GHz Processor
Helio G96, Octa Core, 2 GHz Processor
Dimensity  700 5G, Octa Core, 2.2 GHz Processor
Dimensity  900, Octa Core, 2 GHz Processor
Helio G96, Octa Core, 2.05 GHz Processor
Dimensity 920 5G, Octa Core, 2.5 GHz Processor
Helio A22, Quad Core, 2 GHz Processor
Snapdragon 8 Gen2, Octa Core, 3.2 GHz Processor
Snapdragon  695, Octa Core, 2.2 GHz Processor
Dimensity  700 5G, Octa Core, 2.2 GHz Processor
Dimensity  8200, Octa Core, 3.1 GHz Processor
Snapdragon 695, Octa Core, 2.2 GHz Processor
Quad Core, 1.6 GHz Processor
Tiger T7150, Quad Core, 1.8 GHz Processor
Helio  P22 , Octa Core, 2 GHz Processor
Helio  G85, Octa Core, 2 GHz Processor
Snapdragon 888, Octa Core, 2.84 GHz Processor
Snapdragon  8 Gen1, Octa Core, 3 GHz Processor
Snapdragon 888+, Octa Core, 2.9 GHz Processor
Tiger  T616, Octa Core, 1.8 GHz Processor
Dimensity 8100-Max, Octa Core, 2.85 GHz Processor
Snapdragon 695, Octa Core, 2.2 GHz Processor
Snapdragon 695 , Octa Core, 2.2 GHz Processor
Helio P35, Octa Core, 2.3 GHz Processor
Snapdragon 680, Octa Core, 2.4 GHz Processor
Octa Core, 2 GHz Processor
Snapdragon 8+ Gen1, Octa Core, 3.2 GHz Processor
Snapdragon 8 Gen2, Octa Core, 3.2 GHz Processor
Snapdragon 680, Octa Core, 2.4 GHz Processor
Dimensity 700 5G, Octa Core, 2.2 GHz Processor
Snapdragon 778G Plus, Octa Core, 2.5 GHz Processor
Exynos 1380, Octa Core Processor
Helio G99, Octa Core, 2.2 GHz Processor
Dimensity 1080, Octa Core, 2.6 GHz Processor
Bionic  A16, Hexa Core Processor
Dimensity 1300, Octa Core, 3 GHz Processor
Dimensity  810 5G, Octa Core, 2.4 GHz Processor
Snapdragon  695, Octa Core, 2.2 GHz Processor
Dimensity 700 5G, Octa Core, 2.2 GHz Processor
Snapdragon 695, Octa Core, 2.2 GHz Processor
Google  Tensor G2, Octa Core, 2.85 GHz Processor
Helio G88, Octa Core, 2 GHz Processor
Dimensity 1200, Octa Core, 3 GHz Processor
Helio P35, Octa Core, 2.3 GHz Processor
Snapdragon  8+ Gen1, Octa Core, 3.2 GHz Processor
Dimensity  920 5G, Octa Core, 2.5 GHz Processor
Dimensity 810 5G, Octa Core, 2.4 GHz Processor
Snapdragon 778G+, Octa Core, 2.5 GHz Processor
Snapdragon  680, Octa Core, 2.4 GHz Processor
Helio, Octa Core Processor
Helio G35, Octa Core, 2.3 GHz Processor
Dimensity 810 5G, Octa Core, 2.4 GHz Processor
Snapdragon 870, Octa Core, 3.2 GHz Processor
Dimensity 8100-Max, Octa Core, 2.85 GHz Processor
Snapdragon  8 Gen1, Octa Core, 3 GHz Processor
Snapdragon 8 Gen2, Octa Core, 3.2 GHz Processor
Snapdragon 680, Octa Core, 2.4 GHz Processor
Snapdragon 680, Octa Core, 2.4 GHz Processor
Dimensity 700 5G, Octa Core, 2.2 GHz Processor
Snapdragon 680, Octa Core, 2.4 GHz Processor
Snapdragon  8+ Gen1 , Octa Core, 3.2 GHz Processor
Helio P35, Octa Core, 2.3 GHz Processor
Snapdragon  695, Octa Core, 2.2 GHz Processor
Helio G96, Octa Core, 2.05 GHz Processor
Dimensity 1080, Octa Core, 2.6 GHz Processor
Helio G35, Octa Core, 2.3 GHz Processor
Snapdragon 778G+, Octa Core Processor
Snapdragon 778G, Octa Core, 2.4 GHz Processor
Google Tensor G2, Octa Core, 2.85 GHz Processor
Dimensity  810 5G, Octa Core, 2.4 GHz Processor
Snapdragon  680, Octa Core, 2.4 GHz Processor
Bionic A15, Hexa Core, 3.22 GHz Processor
Dimensity 930, Octa Core, 2.2 GHz Processor
Snapdragon 8 Gen2, Octa Core, 3.2 GHz Processor
Helio  G85, Octa Core, 2 GHz Processor
Dimensity 9000, Octa Core, 3.05 GHz Processor
Helio G99, Octa Core, 2.2 GHz Processor
Snapdragon  695 , Octa Core, 2.2 GHz Processor
Snapdragon 695, Octa Core, 2.2 GHz Processor
Snapdragon 695, Octa Core, 2.2 GHz Processor
Exynos  2300, Octa Core Processor
Snapdragon  8 Gen1, Octa Core, 3 GHz Processor
Snapdragon  480 , Octa Core, 2 GHz Processor
Helio  G85, Octa Core, 2 GHz Processor
Dimensity 700 5G, Octa Core, 2.2 GHz Processor
Dimensity 900, Octa Core, 2.4 GHz Processor
Helio G35, Octa Core, 2.3 GHz Processor
Apple  A13
Exynos 1280, Octa Core, 2.4 GHz Processor
Dimensity 810 5G, Octa Core, 2.4 GHz Processor
Dimensity  1200 Max, Octa Core, 3 GHz Processor
Snapdragon 8+ Gen1, Octa Core, 3.2 GHz Processor
Snapdragon 712, Octa Core, 2.3 GHz Processor
Snapdragon 8+ Gen1, Octa Core, 3.2 GHz Processor
Helio G80, Octa Core, 2 GHz Processor
Snapdragon 205 , Dual Core, 1.1 GHz Processor
Google  Tensor, Octa Core, 2.8 GHz Processor
Helio G85, Octa Core, 2 GHz Processor
Dimensity 700 5G, Octa Core, 2.2 GHz Processor
 Snapdragon  695, Octa Core, 2.2 GHz Processor
Snapdragon 8 Gen1, Octa Core, 3 GHz Processor
Bionic A15, Hexa Core, 3.22 GHz Processor
Helio G88, Octa Core, 2 GHz Processor
Tiger T612, Octa Core, 1.82 GHz Processor
Snapdragon 8+ Gen1, Octa Core, 3.2 GHz Processor
Dimensity  810 5G, Octa Core, 2.4 GHz Processor
Bionic A16
Dimensity 700 , Octa Core, 2.2 GHz Processor
Dimensity 8200, Octa Core, 3.1 GHz Processor
Snapdragon  680, Octa Core, 2.4 GHz Processor
Dimensity 1080, Octa Core, 2.6 GHz Processor
Snapdragon 778G, Octa Core, 2.4 GHz Processor
Helio  G99, Octa Core, 2.2 GHz Processor
Dimensity 810, Octa Core, 2.4 GHz Processor
Bionic  A16, Hexa Core Processor
Exynos  850, Octa Core, 2 GHz Processor
Dimensity  810 5G, Octa Core, 2.4 GHz Processor
Helio G95, Octa Core, 2.05 GHz Processor
SC9863A, Octa Core, 1.6 GHz Processor
Snapdragon 695, Octa Core, 2.2 GHz Processor
Snapdragon 8+ Gen1, Octa Core, 3.2 GHz Processor
Snapdragon  695, Octa Core, 2.2 GHz Processor
Snapdragon 8 Gen2, Octa Core, 3.2 GHz Processor
Helio  G25, Octa Core, 2 GHz Processor
Helio P35, Octa Core, 2.3 GHz Processor
Dimensity  8100, Octa Core, 2.85 GHz Processor
Tiger T612, Octa Core, 1.82 GHz Processor
Snapdragon  480+, Octa Core, 2.2 GHz Processor
Snapdragon 680, Octa Core, 2.4 GHz Processor
Snapdragon  778G , Octa Core, 2.4 GHz Processor
Snapdragon 888, Octa Core, 2.84 GHz Processor
Bionic A14, Hexa Core, 3.1 GHz Processor
Snapdragon 8+ Gen1, Octa Core, 3.2 GHz Processor
Octa Core, 2 GHz Processor
Dimensity 900, Octa Core, 2 GHz Processor
Snapdragon  888 , Octa Core, 2.84 GHz Processor
Exynos 1280, Octa Core, 2.4 GHz Processor
Snapdragon  8 Gen1, Octa Core, 3 GHz Processor
Snapdragon 695, Octa Core, 2.2 GHz Processor
Quad Core, 1.3 GHz Processor
Dimensity  900, Octa Core, 2.4 GHz Processor
Dimensity 700, Octa Core, 2.2 GHz Processor
Dimensity 9000 Plus, Octa Core, 3.2 GHz Processor
Snapdragon 695, Octa Core, 2.2 GHz Processor
Snapdragon 8 Gen2, Octa Core, 3.2 GHz Processor
Snapdragon  8+ Gen1, Octa Core, 3.2 GHz Processor
Snapdragon 865, Octa Core, 2.84 GHz Processor
Bionic A15, Hexa Core, 3.22 GHz Processor
Exynos  1280, Octa Core, 2.4 GHz Processor
Helio G37, Octa Core, 2.3 GHz Processor
Google Tensor, Octa Core, 2.8 GHz Processor
Snapdragon 732G , Octa Core, 2.3 GHz Processor
Exynos  2100, Octa Core, 2.9 GHz Processor
Helio G37, Octa Core, 2.3 GHz Processor
Snapdragon 680, Octa Core, 2.4 GHz Processor
Snapdragon  695, Octa Core, 2.2 GHz Processor
Snapdragon  778G, Octa Core, 2.4 GHz Processor
Snapdragon 778G, Octa Core, 2.4 GHz Processor
Snapdragon  778G, Octa Core, 2.4 GHz Processor
Snapdragon  870, Octa Core, 3.2 GHz Processor
Helio G88, Octa Core, 2 GHz Processor
Unisoc  SC9836A, Quad Core, 1.6 GHz Processor
Snapdragon  732G, Octa Core, 2.3 GHz Processor
Snapdragon 888, Octa Core, 2.84 GHz Processor
Helio  G96, Octa Core, 2.05 GHz Processor
Helio G35, Octa Core, 2.3 GHz Processor
Dimensity 810 5G, Octa Core, 2.4 GHz Processor
Helio P35, Octa Core, 2.3 GHz Processor
Helio G96, Octa Core, 2.05 GHz Processor
Snapdragon 695, Octa Core, 2.2 GHz Processor
Bionic A15, Hexa Core, 3.22 GHz Processor
Snapdragon 8 Gen2, Octa Core, 3.2 GHz Processor
Dimensity 9200, Octa Core, 3.05 GHz Processor
Snapdragon 480+, Octa Core, 2.2 GHz Processor
Helio  G37, Octa Core, 2.3 GHz Processor
Helio G25, Octa Core, 2 GHz Processor
Qualcomm 215, Quad Core, 1.3 GHz Processor
Helio P22, Octa Core, 2 GHz Processor
Snapdragon 8 Gen2, Octa Core, 3.2 GHz Processor
Unisoc SC9863A, Octa Core, 1.6 GHz Processor
Snapdragon 680, Octa Core, 2.4 GHz Processor
Helio G35, Octa Core, 2.3 GHz Processor
Helio G25, Octa Core, 2 GHz Processor
Snapdragon  870, Octa Core, 3.2 GHz Processor
Snapdragon 680, Octa Core, 2.4 GHz Processor
Snapdragon  8+ Gen1, Octa Core, 3.2 GHz Processor
Snapdragon  888+, Octa Core, 2.9 GHz Processor
Bionic A14, Hexa Core, 3.1 GHz Processor
Snapdragon 8+ Gen 2, Octa Core Processor
Dimensity 9000, Octa Core, 3.05 GHz Processor
Snapdragon 8+ Gen1, Octa Core, 3.2 GHz Processor
Helio G37, Octa Core, 2.3 GHz Processor
Exynos  2100, Octa Core, 2.9 GHz Processor
Dimensity  810 5G, Octa Core, 2.4 GHz Processor
Snapdragon 888, Octa Core, 2.84 GHz Processor
Snapdragon 765G , Octa Core, 2.4 GHz Processor
Snapdragon  732G, Octa Core, 2.3 GHz Processor
Exynos 990, Octa Core, 2.73 GHz Processor
Snapdragon 855, Octa Core, 2.8 GHz Processor
Exynos 9820, Octa Core, 2.7 GHz Processor
No Wifi
Dimensity  930, Octa Core, 2.2 GHz Processor
Snapdragon  680, Octa Core, 2.4 GHz Processor
Snapdragon  888 , Octa Core, 2.84 GHz Processor
Exynos  2100, Octa Core, 2.9 GHz Processor
Snapdragon 730, Octa Core, 2.2 GHz Processor
Helio P35, Octa Core, 2.3 GHz Processor
Unisoc, Octa Core Processor
Unisoc  T606, Octa Core, 2 GHz Processor
Snapdragon  695 , Octa Core, 2.2 GHz Processor
Snapdragon 778G, Octa Core, 2.4 GHz Processor
Dimensity  920 5G, Octa Core, 2.5 GHz Processor
Exynos 850, Octa Core, 2 GHz Processor
Snapdragon  680, Octa Core, 2.4 GHz Processor
Dimensity 700 5G, Octa Core, 2.2 GHz Processor
Snapdragon 662 , Octa Core, 2 GHz Processor
Dimensity 9000 Plus, Octa Core, 3.2 GHz Processor
Helio G80, Octa Core, 2 GHz Processor
Helio G95, Octa Core, 2 GHz Processor
Snapdragon  695, Octa Core, 2.2 GHz Processor
Snapdragon 720G, Octa Core, 2.3 GHz Processor
Dimensity 700 5G, Octa Core, 2.2 GHz Processor
Dimensity  810 5G, Octa Core, 2.4 GHz Processor
Spreadtrum  SC7731E, Quad Core, 1.3 GHz Processor
Dual Core, 1 GHz Processor
Snapdragon  8+ Gen1, Octa Core, 3.2 GHz Processor
Bionic  A17, Octa Core Processor
Helio A22, Quad Core, 2 GHz Processor
Snapdragon  8+ Gen1, Octa Core, 3.2 GHz Processor
Snapdragon  680, Octa Core, 2.4 GHz Processor
Dimensity  810 5G, Octa Core, 2.4 GHz Processor
Snapdragon  8 Gen1, Octa Core, 3 GHz Processor
Dimensity 1200, Octa Core, 3 GHz Processor
Dimensity  920 5G, Octa Core, 2.5 GHz Processor
Snapdragon 8 Gen2, Octa Core, 3.2 GHz Processor
Snapdragon  810, Octa Core, 2.4 GHz Processor
Snapdragon  778G, Octa Core, 2.4 GHz Processor
Unisoc  T606, Octa Core, 1.6 GHz Processor
Snapdragon  480 , Octa Core, 2 GHz Processor
Snapdragon 870, Octa Core, 3.2 GHz Processor
Dimensity 900, Octa Core, 2 GHz Processor
Snapdragon 865, Octa Core, 2.84 GHz Processor
Helio  G25, Octa Core, 2 GHz Processor
Snapdragon 778G, Octa Core, 2.4 GHz Processor
Bionic  A16, Hexa Core Processor
Snapdragon 695, Octa Core, 2.2 GHz Processor
Snapdragon 8+ Gen1, Octa Core, 3.2 GHz Processor
Snapdragon 8+ Gen1, Octa Core, 3.2 GHz Processor
Snapdragon  778G Plus, Octa Core, 2.5 GHz Processor
Snapdragon  8 Gen1, Octa Core, 3 GHz Processor
Dimensity 1200, Octa Core, 3 GHz Processor
Helio G35, Octa Core, 2.3 GHz Processor
Snapdragon  888 , Octa Core, 2.84 GHz Processor
Snapdragon 775
Snapdragon 678, Octa Core, 2.2 GHz Processor
Snapdragon 801, Octa Core, 1.5 GHz Processor
Helio G80, Octa Core, 2 GHz Processor
Helio G96, Octa Core, 2.05 GHz Processor
Snapdragon 8+ Gen1, Octa Core, 3.2 GHz Processor
Dimensity  810 5G, Octa Core, 2.4 GHz Processor
Helio P22, Octa Core, 2 GHz Processor
Helio G37, Octa Core, 2.3 GHz Processor
Helio  G96, Octa Core, 2.05 GHz Processor
Bionic  A15, Hexa Core, 3.22 GHz Processor
Snapdragon  720G, Octa Core, 2.3 GHz Processor
Snapdragon 860, Octa Core, 2.96 GHz Processor
Helio G25, Octa Core, 2 GHz Processor
Helio G80, Octa Core, 2 GHz Processor
Helio G85, Octa Core, 2 GHz Processor
Dimensity 9000 Plus, Octa Core, 3.2 GHz Processor
Dimensity 1080, Octa Core, 2.6 GHz Processor
Helio A22, Quad Core, 2 GHz Processor
Bionic  A16
Tiger  T616, Octa Core, 1.8 GHz Processor
Helio G37, Octa Core, 2.3 GHz Processor
Dimensity  9000, Octa Core, 3.05 GHz Processor
Helio G80, Octa Core, 2 GHz Processor
Helio G95, Octa Core, 2.05 GHz Processor
Helio P35, Octa Core, 2.3 GHz Processor
Helio  G85, Octa Core, 2 GHz Processor
Snapdragon 8+ Gen1, Octa Core, 3.2 GHz Processor

In [111]:
for i in df["processor"]:
    if "Processor" not in i:
        print(i)

Bionic  A16
Apple  A13
Bionic A16
No Wifi
Snapdragon 775
Bionic  A16
No Wifi
No Wifi
No 3G
No Wifi
No Wifi
1 GB RAM, 4 GB inbuilt
No 3G
Unisoc T117
4 MB RAM, 4 MB inbuilt
1450 mAh Battery
4 MB RAM, 4 MB inbuilt
32 MB RAM, 32 MB inbuilt
4 MB RAM, 4 MB inbuilt
Helio MT6260A
800 mAh Battery
Bionic  A16
2000 mAh Battery
32 GB inbuilt
52 MB RAM, 32 MB inbuilt
No 3G
Unisoc T117
1 GB RAM, 8 GB inbuilt
No Wifi
No Wifi
No Wifi
256 MB RAM, 512 MB inbuilt
No Wifi
48 MB RAM, 128 MB inbuilt
8 MB RAM, 16 MB inbuilt
No 3G

In [112]:
for i in df.index:
    if "Processor" not in df["processor"][i]:
        print(i , df["processor"][i])

152 Bionic  A16
263 Apple  A13
282 Bionic A16
376 No Wifi
429 Snapdragon 775
448 Bionic  A16
473 No Wifi
532 No Wifi
551 No 3G
573 No Wifi
582 No Wifi
608 1 GB RAM, 4 GB inbuilt
611 No 3G
627 Unisoc T117
640 4 MB RAM, 4 MB inbuilt
645 1450 mAh Battery
647 4 MB RAM, 4 MB inbuilt
657 32 MB RAM, 32 MB inbuilt
665 4 MB RAM, 4 MB inbuilt
685 Helio MT6260A
699 800 mAh Battery
728 Bionic  A16
748 2000 mAh Battery
754 32 GB inbuilt
757 52 MB RAM, 32 MB inbuilt
817 No 3G
852 Unisoc T117
857 1 GB RAM, 8 GB inbuilt
881 No Wifi
882 No Wifi
917 No Wifi
925 256 MB RAM, 512 MB inbuilt
927 No Wifi
930 48 MB RAM, 128 MB inbuilt
988 8 MB RAM, 16 MB inbuilt
1000 No 3G

In [113]:
df[~df["processor"].str.contains("Processor")].index

Index([ 152,  263,  282,  376,  429,  448,  473,  532,  551,  573,  582,  608,
        611,  627,  640,  645,  647,  657,  665,  685,  699,  728,  748,  754,
        757,  817,  852,  857,  881,  882,  917,  925,  927,  930,  988, 1000],
      dtype='int64')

In [114]:
for i in df.index:
    if "RAM" not  in df["ram"][i]:
        print(i,df["ram"][i])

376 Unisoc T107
439 64 GB inbuilt
483 512 GB inbuilt
532 Single Core, 208 MHz Processor
551 T117
582 Unisoc T107
608 1325 mAh Battery
611 Dual Core, 500 MHz Processor
640 800 mAh Battery
645 3.6 inches, 240 x 320 px Display
647 1750 mAh Battery
657 200 mAh Battery
665 1200 mAh Battery
699 1.5 inches, 120 x 120 px Display
748 2.4 inches, 240 x 320 px Display
754 4 inches, 640 x 1136 px Display
757 1000 mAh Battery
762 64 GB inbuilt
817 T117
857 1470 mAh Battery
882 Unisoc T107
917 4 MB inbuilt
925 1200 mAh Battery
927 800 mAh Battery
930 1800 mAh Battery
988 1200 mAh Battery
1000 No Wifi

In [115]:
df[~df["ram"].str.contains("ram")].index

RangeIndex(start=0, stop=1020, step=1)

In [116]:
for i in df.index:
    if "Battery" not in df["battery"][i]:
        print(i, df["battery"][i])

111 6.1 inches, 1170 x 2532 px Display with Large Notch
149 5.4 inches, 1080 x 2340 px Display
307 6.1 inches, 1170 x 2532 px Display with Large Notch
363 5.4 inches, 1080 x 2340 px Display
376 48 MB RAM, 128 MB inbuilt
439 4.7 inches, 750 x 1334 px Display
448 6.06 inches, 1170 x 2532 px, 120 Hz Display with Punch Hole
551 64 MB RAM, 128 MB inbuilt
582 48 MB RAM, 128 MB inbuilt
608 4 inches, 720 x 1280 px Display
611 32 MB RAM, 32 MB inbuilt
628 6.1 inches, 1170 x 2532 px Display with Large Notch
640 1.77 inches, 128 x 160 px Display
645 5 MP Rear & 5 MP Front Camera
647 1.8 inches, 160 x 128 px Display
657 0.49 inches, 64 x 32 px Display
665 1.8 inches, 160 x 128 px Display
699 No Rear Camera
748 0.3 MP Rear & 0.3 MP Front Camera
754 8 MP Rear & 1.2 MP Front Camera
757 1.8 inches, 128 x 160 px Display
762 6.1 inches, 750 x 1580 px Display
817 48 MB RAM, 128 MB inbuilt
853 6.1 inches, 1170 x 2532 px Display with Large Notch
857 2.8 inches, 240 x 320 px Display
882 48 MB RAM, 128 MB inbuilt
913 5.4 inches, 1080 x 2340 px Display
914 6.1 inches, 1170 x 2532 px Display with Large Notch
925 2.4 inches, 240 x 320 px Display
927 1.5 inches, 128 x 128 px Display
930 2.4 inches, 240 x 360 px Display
988 2.4 inches, 240 x 320 px Display
1000 32 MB RAM, 32 MB inbuilt

In [117]:
df[~df["battery"].str.contains("Battery")]

,model,price,rating,sim,processor,ram,battery,display,camera,card,os
111,Apple iPhone 12,51999,74.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Bionic A14, Hexa Core, 3.1 GHz Processor","4 GB RAM, 64 GB inbuilt","6.1 inches, 1170 x 2532 px Display with Large ...",12 MP + 12 MP Dual Rear & 12 MP Front Camera,Memory Card Not Supported,iOS v14,No FM Radio
149,Apple iPhone 12 Mini,40999,74.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Bionic A14, Hexa Core, 3.1 GHz Processor","4 GB RAM, 64 GB inbuilt","5.4 inches, 1080 x 2340 px Display",12 MP + 12 MP Dual Rear & 12 MP Front Camera,Memory Card Not Supported,iOS v14,No FM Radio
307,Apple iPhone 12 (128GB),55999,75.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Bionic A14, Hexa Core, 3.1 GHz Processor","4 GB RAM, 128 GB inbuilt","6.1 inches, 1170 x 2532 px Display with Large ...",12 MP + 12 MP Dual Rear & 12 MP Front Camera,Memory Card Not Supported,iOS v14,No FM Radio
363,Apple iPhone 12 Mini (128GB),45999,75.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Bionic A14, Hexa Core, 3.1 GHz Processor","4 GB RAM, 128 GB inbuilt","5.4 inches, 1080 x 2340 px Display",12 MP + 12 MP Dual Rear & 12 MP Front Camera,Memory Card Not Supported,iOS v14,No FM Radio
376,Nokia 2660 Flip,4649,NaN,"Dual Sim, 3G, 4G",No Wifi,Unisoc T107,"48 MB RAM, 128 MB inbuilt",1450 mAh Battery,"2.8 inches, 240 x 320 px Display",Dual Display,0.3 MP Rear Camera
439,Apple iPhone SE 3 2022,43900,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Bionic A15, Hexa Core, 3.22 GHz Processor",64 GB inbuilt,"4.7 inches, 750 x 1334 px Display",12 MP Rear & 7 MP Front Camera,Memory Card Not Supported,iOS v15,No FM Radio
448,Apple iPhone 15 Pro,130990,75.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC",Bionic A16,"8 GB RAM, 128 GB inbuilt","6.06 inches, 1170 x 2532 px, 120 Hz Display wi...",50 MP + 12 MP + 12 MP Triple Rear & 12 MP Fron...,Memory Card Not Supported,iOS v15,No FM Radio
551,itel Magic 2 4G,2399,NaN,"Dual Sim, 3G, 4G, VoLTE, Wi-Fi",No 3G,T117,"64 MB RAM, 128 MB inbuilt",1900 mAh Battery,"2.4 inches, 240 x 320 px Display",1.3 MP Rear Camera,"Memory Card Supported, upto 64 GB"
582,Nokia 8210 4G,3749,NaN,"Dual Sim, 3G, 4G",No Wifi,Unisoc T107,"48 MB RAM, 128 MB inbuilt",1450 mAh Battery,"2.8 inches, 240 x 320 px Display",0.3 MP Rear Camera,"Memory Card Supported, upto 32 GB"
608,Namotel Achhe Din,99,NaN,"Dual Sim, 3G, Wi-Fi","1 GB RAM, 4 GB inbuilt",1325 mAh Battery,"4 inches, 720 x 1280 px Display",2 MP Rear & 0.3 MP Front Camera,Android v5.0 (Lollipop),Bluetooth,NaN
611,Eunity U1 5605N,699,NaN,Dual Sim,No 3G,"Dual Core, 500 MHz Processor","32 MB RAM, 32 MB inbuilt",3000 mAh Battery,"1.8 inches, 128 x 160 px Display",0.3 MP Rear Camera,"Memory Card Supported, upto 16 GB"
628,Apple iPhone 12 Pro (512GB),139900,80.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Bionic A14, Hexa Core, 3.1 GHz Processor","6 GB RAM, 512 GB inbuilt","6.1 inches, 1170 x 2532 px Display with Large ...",12 MP + 12 MP + 12 MP Triple Rear & 12 MP Fron...,Memory Card Not Supported,iOS v14.0,No FM Radio
640,Nokia 105 Plus,1299,NaN,Dual Sim,"4 MB RAM, 4 MB inbuilt",800 mAh Battery,"1.77 inches, 128 x 160 px Display",No Rear Camera,"Memory Card Supported, upto 32 GB",Bluetooth,NaN
645,Nokia 2760 Flip,5490,NaN,"Dual Sim, 3G, 4G, Wi-Fi",1450 mAh Battery,"3.6 inches, 240 x 320 px Display",5 MP Rear & 5 MP Front Camera,"Memory Card Supported, upto 32 GB",Kaios v3.0,Bluetooth,NaN
647,Motorola Moto A10,1339,NaN,Dual Sim,"4 MB RAM, 4 MB inbuilt",1750 mAh Battery,"1.8 inches, 160 x 128 px Display",No Rear Camera,"Memory Card Supported, upto 32 GB",NaN,NaN
657,Zanco Tiny T1,2799,NaN,Single Sim,"32 MB RAM, 32 MB inbuilt",200 mAh Battery,"0.49 inches, 64 x 32 px Display",No Rear Camera,No FM Radio,Bluetooth,NaN
665,itel it2163S,958,NaN,Dual Sim,"4 MB RAM, 4 MB inbuilt",1200 mAh Battery,"1.8 inches, 160 x 128 px Display",No Rear Camera,"Memory Card Supported, upto 32 GB",Bluetooth,NaN
699,Samsung Guru GT-E1215,1850,NaN,Single Sim,800 mAh Battery,"1.5 inches, 120 x 120 px Display",No Rear Camera,No FM Radio,NaN,NaN,NaN
748,Nokia 400 4G,3290,NaN,"Dual Sim, 4G, VoLTE, Wi-Fi",2000 mAh Battery,"2.4 inches, 240 x 320 px Display",0.3 MP Rear & 0.3 MP Front Camera,"Memory Card Supported, upto 64 GB",Bluetooth,Browser,NaN
754,Apple iPod Touch (7th Gen),18900,NaN,Wi-Fi,32 GB inbuilt,"4 inches, 640 x 1136 px Display",8 MP Rear & 1.2 MP Front Camera,iOS v12,No FM Radio,Bluetooth,Browser
757,Karbonn KU3i,995,NaN,Dual Sim,"52 MB RAM, 32 MB inbuilt",1000 mAh Battery,"1.8 inches, 128 x 160 px Display",No Rear Camera,"Memory Card Supported, upto 16 GB",Bluetooth,NaN
762,Apple iPhone SE 4,49990,60.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Bionic A15, Hexa Core, 3.22 GHz Processor",64 GB inbuilt,"6.1 inches, 750 x 1580 px Display",12 MP Rear & 10.8 MP Front Camera,Memory Card Not Supported,iOS v16,No FM Radio
817,itel Magic X,2239,NaN,"Dual Sim, 3G, 4G, VoLTE, Wi-Fi",No 3G,T117,"48 MB RAM, 128 MB inbuilt",1200 mAh Battery,"2.4 inches, 240 x 320 px Display",1.3 MP Rear Camera,"Memory Card Supported, upto 64 GB"
853,Apple iPhone 12 Pro (256GB),119900,80.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Bionic A14, Hexa Core, 3.1 GHz Processor","6 GB RAM, 256 GB inbuilt","6.1 inches, 1170 x 2532 px Display with Large ...",12 MP + 12 MP + 12 MP Triple Rear & 12 MP Fron...,Memory Card Not Supported,iOS v14.0,No FM Radio
857,LG Folder 2,11999,NaN,"Single Sim, 3G, 4G, Wi-Fi","1 GB RAM, 8 GB inbuilt",1470 mAh Battery,"2.8 inches, 240 x 320 px Display",2 MP Rear Camera,Memory Card Supported,Bluetooth,NaN
882,Nokia 5710 XpressAudio,4799,NaN,"Dual Sim, 3G, 4G",No Wifi,Unisoc T107,"48 MB RAM, 128 MB inbuilt",1450 mAh Battery,"2.4 inches, 240 x 320 px Display",0.3 MP Rear Camera,"Memory Card Supported, upto 32 GB"
913,Apple iPhone 12 Mini (256GB),55999,75.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Bionic A14, Hexa Core, 3.1 GHz Processor","4 GB RAM, 256 GB inbuilt","5.4 inches, 1080 x 2340 px Display",12 MP + 12 MP Dual Rear & 12 MP Front Camera,Memory Card Not Supported,iOS v14,No FM Radio
914,Apple iPhone 12 (256GB),67999,76.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Bionic A14, Hexa Core, 3.1 GHz Processor","4 GB RAM, 256 GB inbuilt","6.1 inches, 1170 x 2532 px Display with Large ...",12 MP + 12 MP Dual Rear & 12 MP Front Camera,Memory Card Not Supported,iOS v14,No FM Radio
925,Nokia 3310 4G,3999,NaN,"Dual Sim, 3G, 4G, VoLTE, Wi-Fi","256 MB RAM, 512 MB inbuilt",1200 mAh Battery,"2.4 inches, 240 x 320 px Display",2 MP Rear Camera,"Memory Card Supported, upto 32 GB",Bluetooth,Browser
927,Samsung Guru E1200,1685,NaN,Single Sim,No Wifi,800 mAh Battery,"1.5 inches, 128 x 128 px Display",No Rear Camera,No FM Radio,NaN,NaN
930,iKall K88 Pro 4G,2099,NaN,"Dual Sim, 3G, 4G, VoLTE","48 MB RAM, 128 MB inbuilt",1800 mAh Battery,"2.4 inches, 240 x 360 px Display",0.3 MP Rear Camera,"Memory Card Supported, upto 128 GB",Bluetooth,Browser
988,Nokia 5310 Dual Sim,3399,NaN,Dual Sim,"8 MB RAM, 16 MB inbuilt",1200 mAh Battery,"2.4 inches, 240 x 320 px Display",0.3 MP Rear Camera,"Memory Card Supported, upto 32 GB",Bluetooth,Browser
1000,XTouch F40 Flip,1999,NaN,Dual Sim,No 3G,No Wifi,"32 MB RAM, 32 MB inbuilt",800 mAh Battery,"1.77 inches, 240 x 320 px Display",Dual Display,1.3 MP Rear Camera

In [118]:
df[~df["battery"].str.contains("Battery")]

,model,price,rating,sim,processor,ram,battery,display,camera,card,os
111,Apple iPhone 12,51999,74.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Bionic A14, Hexa Core, 3.1 GHz Processor","4 GB RAM, 64 GB inbuilt","6.1 inches, 1170 x 2532 px Display with Large ...",12 MP + 12 MP Dual Rear & 12 MP Front Camera,Memory Card Not Supported,iOS v14,No FM Radio
149,Apple iPhone 12 Mini,40999,74.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Bionic A14, Hexa Core, 3.1 GHz Processor","4 GB RAM, 64 GB inbuilt","5.4 inches, 1080 x 2340 px Display",12 MP + 12 MP Dual Rear & 12 MP Front Camera,Memory Card Not Supported,iOS v14,No FM Radio
307,Apple iPhone 12 (128GB),55999,75.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Bionic A14, Hexa Core, 3.1 GHz Processor","4 GB RAM, 128 GB inbuilt","6.1 inches, 1170 x 2532 px Display with Large ...",12 MP + 12 MP Dual Rear & 12 MP Front Camera,Memory Card Not Supported,iOS v14,No FM Radio
363,Apple iPhone 12 Mini (128GB),45999,75.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Bionic A14, Hexa Core, 3.1 GHz Processor","4 GB RAM, 128 GB inbuilt","5.4 inches, 1080 x 2340 px Display",12 MP + 12 MP Dual Rear & 12 MP Front Camera,Memory Card Not Supported,iOS v14,No FM Radio
376,Nokia 2660 Flip,4649,NaN,"Dual Sim, 3G, 4G",No Wifi,Unisoc T107,"48 MB RAM, 128 MB inbuilt",1450 mAh Battery,"2.8 inches, 240 x 320 px Display",Dual Display,0.3 MP Rear Camera
439,Apple iPhone SE 3 2022,43900,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Bionic A15, Hexa Core, 3.22 GHz Processor",64 GB inbuilt,"4.7 inches, 750 x 1334 px Display",12 MP Rear & 7 MP Front Camera,Memory Card Not Supported,iOS v15,No FM Radio
448,Apple iPhone 15 Pro,130990,75.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC",Bionic A16,"8 GB RAM, 128 GB inbuilt","6.06 inches, 1170 x 2532 px, 120 Hz Display wi...",50 MP + 12 MP + 12 MP Triple Rear & 12 MP Fron...,Memory Card Not Supported,iOS v15,No FM Radio
551,itel Magic 2 4G,2399,NaN,"Dual Sim, 3G, 4G, VoLTE, Wi-Fi",No 3G,T117,"64 MB RAM, 128 MB inbuilt",1900 mAh Battery,"2.4 inches, 240 x 320 px Display",1.3 MP Rear Camera,"Memory Card Supported, upto 64 GB"
582,Nokia 8210 4G,3749,NaN,"Dual Sim, 3G, 4G",No Wifi,Unisoc T107,"48 MB RAM, 128 MB inbuilt",1450 mAh Battery,"2.8 inches, 240 x 320 px Display",0.3 MP Rear Camera,"Memory Card Supported, upto 32 GB"
608,Namotel Achhe Din,99,NaN,"Dual Sim, 3G, Wi-Fi","1 GB RAM, 4 GB inbuilt",1325 mAh Battery,"4 inches, 720 x 1280 px Display",2 MP Rear & 0.3 MP Front Camera,Android v5.0 (Lollipop),Bluetooth,NaN
611,Eunity U1 5605N,699,NaN,Dual Sim,No 3G,"Dual Core, 500 MHz Processor","32 MB RAM, 32 MB inbuilt",3000 mAh Battery,"1.8 inches, 128 x 160 px Display",0.3 MP Rear Camera,"Memory Card Supported, upto 16 GB"
628,Apple iPhone 12 Pro (512GB),139900,80.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Bionic A14, Hexa Core, 3.1 GHz Processor","6 GB RAM, 512 GB inbuilt","6.1 inches, 1170 x 2532 px Display with Large ...",12 MP + 12 MP + 12 MP Triple Rear & 12 MP Fron...,Memory Card Not Supported,iOS v14.0,No FM Radio
640,Nokia 105 Plus,1299,NaN,Dual Sim,"4 MB RAM, 4 MB inbuilt",800 mAh Battery,"1.77 inches, 128 x 160 px Display",No Rear Camera,"Memory Card Supported, upto 32 GB",Bluetooth,NaN
645,Nokia 2760 Flip,5490,NaN,"Dual Sim, 3G, 4G, Wi-Fi",1450 mAh Battery,"3.6 inches, 240 x 320 px Display",5 MP Rear & 5 MP Front Camera,"Memory Card Supported, upto 32 GB",Kaios v3.0,Bluetooth,NaN
647,Motorola Moto A10,1339,NaN,Dual Sim,"4 MB RAM, 4 MB inbuilt",1750 mAh Battery,"1.8 inches, 160 x 128 px Display",No Rear Camera,"Memory Card Supported, upto 32 GB",NaN,NaN
657,Zanco Tiny T1,2799,NaN,Single Sim,"32 MB RAM, 32 MB inbuilt",200 mAh Battery,"0.49 inches, 64 x 32 px Display",No Rear Camera,No FM Radio,Bluetooth,NaN
665,itel it2163S,958,NaN,Dual Sim,"4 MB RAM, 4 MB inbuilt",1200 mAh Battery,"1.8 inches, 160 x 128 px Display",No Rear Camera,"Memory Card Supported, upto 32 GB",Bluetooth,NaN
699,Samsung Guru GT-E1215,1850,NaN,Single Sim,800 mAh Battery,"1.5 inches, 120 x 120 px Display",No Rear Camera,No FM Radio,NaN,NaN,NaN
748,Nokia 400 4G,3290,NaN,"Dual Sim, 4G, VoLTE, Wi-Fi",2000 mAh Battery,"2.4 inches, 240 x 320 px Display",0.3 MP Rear & 0.3 MP Front Camera,"Memory Card Supported, upto 64 GB",Bluetooth,Browser,NaN
754,Apple iPod Touch (7th Gen),18900,NaN,Wi-Fi,32 GB inbuilt,"4 inches, 640 x 1136 px Display",8 MP Rear & 1.2 MP Front Camera,iOS v12,No FM Radio,Bluetooth,Browser
757,Karbonn KU3i,995,NaN,Dual Sim,"52 MB RAM, 32 MB inbuilt",1000 mAh Battery,"1.8 inches, 128 x 160 px Display",No Rear Camera,"Memory Card Supported, upto 16 GB",Bluetooth,NaN
762,Apple iPhone SE 4,49990,60.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Bionic A15, Hexa Core, 3.22 GHz Processor",64 GB inbuilt,"6.1 inches, 750 x 1580 px Display",12 MP Rear & 10.8 MP Front Camera,Memory Card Not Supported,iOS v16,No FM Radio
817,itel Magic X,2239,NaN,"Dual Sim, 3G, 4G, VoLTE, Wi-Fi",No 3G,T117,"48 MB RAM, 128 MB inbuilt",1200 mAh Battery,"2.4 inches, 240 x 320 px Display",1.3 MP Rear Camera,"Memory Card Supported, upto 64 GB"
853,Apple iPhone 12 Pro (256GB),119900,80.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Bionic A14, Hexa Core, 3.1 GHz Processor","6 GB RAM, 256 GB inbuilt","6.1 inches, 1170 x 2532 px Display with Large ...",12 MP + 12 MP + 12 MP Triple Rear & 12 MP Fron...,Memory Card Not Supported,iOS v14.0,No FM Radio
857,LG Folder 2,11999,NaN,"Single Sim, 3G, 4G, Wi-Fi","1 GB RAM, 8 GB inbuilt",1470 mAh Battery,"2.8 inches, 240 x 320 px Display",2 MP Rear Camera,Memory Card Supported,Bluetooth,NaN
882,Nokia 5710 XpressAudio,4799,NaN,"Dual Sim, 3G, 4G",No Wifi,Unisoc T107,"48 MB RAM, 128 MB inbuilt",1450 mAh Battery,"2.4 inches, 240 x 320 px Display",0.3 MP Rear Camera,"Memory Card Supported, upto 32 GB"
913,Apple iPhone 12 Mini (256GB),55999,75.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Bionic A14, Hexa Core, 3.1 GHz Processor","4 GB RAM, 256 GB inbuilt","5.4 inches, 1080 x 2340 px Display",12 MP + 12 MP Dual Rear & 12 MP Front Camera,Memory Card Not Supported,iOS v14,No FM Radio
914,Apple iPhone 12 (256GB),67999,76.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Bionic A14, Hexa Core, 3.1 GHz Processor","4 GB RAM, 256 GB inbuilt","6.1 inches, 1170 x 2532 px Display with Large ...",12 MP + 12 MP Dual Rear & 12 MP Front Camera,Memory Card Not Supported,iOS v14,No FM Radio
925,Nokia 3310 4G,3999,NaN,"Dual Sim, 3G, 4G, VoLTE, Wi-Fi","256 MB RAM, 512 MB inbuilt",1200 mAh Battery,"2.4 inches, 240 x 320 px Display",2 MP Rear Camera,"Memory Card Supported, upto 32 GB",Bluetooth,Browser
927,Samsung Guru E1200,1685,NaN,Single Sim,No Wifi,800 mAh Battery,"1.5 inches, 128 x 128 px Display",No Rear Camera,No FM Radio,NaN,NaN
930,iKall K88 Pro 4G,2099,NaN,"Dual Sim, 3G, 4G, VoLTE","48 MB RAM, 128 MB inbuilt",1800 mAh Battery,"2.4 inches, 240 x 360 px Display",0.3 MP Rear Camera,"Memory Card Supported, upto 128 GB",Bluetooth,Browser
988,Nokia 5310 Dual Sim,3399,NaN,Dual Sim,"8 MB RAM, 16 MB inbuilt",1200 mAh Battery,"2.4 inches, 240 x 320 px Display",0.3 MP Rear Camera,"Memory Card Supported, upto 32 GB",Bluetooth,Browser
1000,XTouch F40 Flip,1999,NaN,Dual Sim,No 3G,No Wifi,"32 MB RAM, 32 MB inbuilt",800 mAh Battery,"1.77 inches, 240 x 320 px Display",Dual Display,1.3 MP Rear Camera

In [119]:
for i in df.index:
    if "Display" not in df["display"][i]:
        print(i , df["display"][i])

111 12 MP + 12 MP Dual Rear & 12 MP Front Camera
149 12 MP + 12 MP Dual Rear & 12 MP Front Camera
307 12 MP + 12 MP Dual Rear & 12 MP Front Camera
363 12 MP + 12 MP Dual Rear & 12 MP Front Camera
376 1450 mAh Battery
439 12 MP Rear & 7 MP Front Camera
448 50 MP + 12 MP + 12 MP Triple Rear & 12 MP Front Camera
551 1900 mAh Battery
582 1450 mAh Battery
608 2 MP Rear & 0.3 MP Front Camera
611 3000 mAh Battery
628 12 MP + 12 MP + 12 MP Triple Rear & 12 MP Front Camera
640 No Rear Camera
645 Memory Card Supported, upto 32 GB
647 No Rear Camera
657 No Rear Camera
665 No Rear Camera
699 No FM Radio
748 Memory Card Supported, upto 64 GB
754 iOS v12
757 No Rear Camera
762 12 MP Rear & 10.8 MP Front Camera
817 1200 mAh Battery
853 12 MP + 12 MP + 12 MP Triple Rear & 12 MP Front Camera
857 2 MP Rear Camera
882 1450 mAh Battery
913 12 MP + 12 MP Dual Rear & 12 MP Front Camera
914 12 MP + 12 MP Dual Rear & 12 MP Front Camera
925 2 MP Rear Camera
927 No Rear Camera
930 0.3 MP Rear Camera
988 0.3 MP Rear Camera
1000 800 mAh Battery

In [120]:
df[~df["display"].str.contains("Display")]

,model,price,rating,sim,processor,ram,battery,display,camera,card,os
111,Apple iPhone 12,51999,74.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Bionic A14, Hexa Core, 3.1 GHz Processor","4 GB RAM, 64 GB inbuilt","6.1 inches, 1170 x 2532 px Display with Large ...",12 MP + 12 MP Dual Rear & 12 MP Front Camera,Memory Card Not Supported,iOS v14,No FM Radio
149,Apple iPhone 12 Mini,40999,74.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Bionic A14, Hexa Core, 3.1 GHz Processor","4 GB RAM, 64 GB inbuilt","5.4 inches, 1080 x 2340 px Display",12 MP + 12 MP Dual Rear & 12 MP Front Camera,Memory Card Not Supported,iOS v14,No FM Radio
307,Apple iPhone 12 (128GB),55999,75.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Bionic A14, Hexa Core, 3.1 GHz Processor","4 GB RAM, 128 GB inbuilt","6.1 inches, 1170 x 2532 px Display with Large ...",12 MP + 12 MP Dual Rear & 12 MP Front Camera,Memory Card Not Supported,iOS v14,No FM Radio
363,Apple iPhone 12 Mini (128GB),45999,75.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Bionic A14, Hexa Core, 3.1 GHz Processor","4 GB RAM, 128 GB inbuilt","5.4 inches, 1080 x 2340 px Display",12 MP + 12 MP Dual Rear & 12 MP Front Camera,Memory Card Not Supported,iOS v14,No FM Radio
376,Nokia 2660 Flip,4649,NaN,"Dual Sim, 3G, 4G",No Wifi,Unisoc T107,"48 MB RAM, 128 MB inbuilt",1450 mAh Battery,"2.8 inches, 240 x 320 px Display",Dual Display,0.3 MP Rear Camera
439,Apple iPhone SE 3 2022,43900,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Bionic A15, Hexa Core, 3.22 GHz Processor",64 GB inbuilt,"4.7 inches, 750 x 1334 px Display",12 MP Rear & 7 MP Front Camera,Memory Card Not Supported,iOS v15,No FM Radio
448,Apple iPhone 15 Pro,130990,75.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC",Bionic A16,"8 GB RAM, 128 GB inbuilt","6.06 inches, 1170 x 2532 px, 120 Hz Display wi...",50 MP + 12 MP + 12 MP Triple Rear & 12 MP Fron...,Memory Card Not Supported,iOS v15,No FM Radio
551,itel Magic 2 4G,2399,NaN,"Dual Sim, 3G, 4G, VoLTE, Wi-Fi",No 3G,T117,"64 MB RAM, 128 MB inbuilt",1900 mAh Battery,"2.4 inches, 240 x 320 px Display",1.3 MP Rear Camera,"Memory Card Supported, upto 64 GB"
582,Nokia 8210 4G,3749,NaN,"Dual Sim, 3G, 4G",No Wifi,Unisoc T107,"48 MB RAM, 128 MB inbuilt",1450 mAh Battery,"2.8 inches, 240 x 320 px Display",0.3 MP Rear Camera,"Memory Card Supported, upto 32 GB"
608,Namotel Achhe Din,99,NaN,"Dual Sim, 3G, Wi-Fi","1 GB RAM, 4 GB inbuilt",1325 mAh Battery,"4 inches, 720 x 1280 px Display",2 MP Rear & 0.3 MP Front Camera,Android v5.0 (Lollipop),Bluetooth,NaN
611,Eunity U1 5605N,699,NaN,Dual Sim,No 3G,"Dual Core, 500 MHz Processor","32 MB RAM, 32 MB inbuilt",3000 mAh Battery,"1.8 inches, 128 x 160 px Display",0.3 MP Rear Camera,"Memory Card Supported, upto 16 GB"
628,Apple iPhone 12 Pro (512GB),139900,80.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Bionic A14, Hexa Core, 3.1 GHz Processor","6 GB RAM, 512 GB inbuilt","6.1 inches, 1170 x 2532 px Display with Large ...",12 MP + 12 MP + 12 MP Triple Rear & 12 MP Fron...,Memory Card Not Supported,iOS v14.0,No FM Radio
640,Nokia 105 Plus,1299,NaN,Dual Sim,"4 MB RAM, 4 MB inbuilt",800 mAh Battery,"1.77 inches, 128 x 160 px Display",No Rear Camera,"Memory Card Supported, upto 32 GB",Bluetooth,NaN
645,Nokia 2760 Flip,5490,NaN,"Dual Sim, 3G, 4G, Wi-Fi",1450 mAh Battery,"3.6 inches, 240 x 320 px Display",5 MP Rear & 5 MP Front Camera,"Memory Card Supported, upto 32 GB",Kaios v3.0,Bluetooth,NaN
647,Motorola Moto A10,1339,NaN,Dual Sim,"4 MB RAM, 4 MB inbuilt",1750 mAh Battery,"1.8 inches, 160 x 128 px Display",No Rear Camera,"Memory Card Supported, upto 32 GB",NaN,NaN
657,Zanco Tiny T1,2799,NaN,Single Sim,"32 MB RAM, 32 MB inbuilt",200 mAh Battery,"0.49 inches, 64 x 32 px Display",No Rear Camera,No FM Radio,Bluetooth,NaN
665,itel it2163S,958,NaN,Dual Sim,"4 MB RAM, 4 MB inbuilt",1200 mAh Battery,"1.8 inches, 160 x 128 px Display",No Rear Camera,"Memory Card Supported, upto 32 GB",Bluetooth,NaN
699,Samsung Guru GT-E1215,1850,NaN,Single Sim,800 mAh Battery,"1.5 inches, 120 x 120 px Display",No Rear Camera,No FM Radio,NaN,NaN,NaN
748,Nokia 400 4G,3290,NaN,"Dual Sim, 4G, VoLTE, Wi-Fi",2000 mAh Battery,"2.4 inches, 240 x 320 px Display",0.3 MP Rear & 0.3 MP Front Camera,"Memory Card Supported, upto 64 GB",Bluetooth,Browser,NaN
754,Apple iPod Touch (7th Gen),18900,NaN,Wi-Fi,32 GB inbuilt,"4 inches, 640 x 1136 px Display",8 MP Rear & 1.2 MP Front Camera,iOS v12,No FM Radio,Bluetooth,Browser
757,Karbonn KU3i,995,NaN,Dual Sim,"52 MB RAM, 32 MB inbuilt",1000 mAh Battery,"1.8 inches, 128 x 160 px Display",No Rear Camera,"Memory Card Supported, upto 16 GB",Bluetooth,NaN
762,Apple iPhone SE 4,49990,60.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Bionic A15, Hexa Core, 3.22 GHz Processor",64 GB inbuilt,"6.1 inches, 750 x 1580 px Display",12 MP Rear & 10.8 MP Front Camera,Memory Card Not Supported,iOS v16,No FM Radio
817,itel Magic X,2239,NaN,"Dual Sim, 3G, 4G, VoLTE, Wi-Fi",No 3G,T117,"48 MB RAM, 128 MB inbuilt",1200 mAh Battery,"2.4 inches, 240 x 320 px Display",1.3 MP Rear Camera,"Memory Card Supported, upto 64 GB"
853,Apple iPhone 12 Pro (256GB),119900,80.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Bionic A14, Hexa Core, 3.1 GHz Processor","6 GB RAM, 256 GB inbuilt","6.1 inches, 1170 x 2532 px Display with Large ...",12 MP + 12 MP + 12 MP Triple Rear & 12 MP Fron...,Memory Card Not Supported,iOS v14.0,No FM Radio
857,LG Folder 2,11999,NaN,"Single Sim, 3G, 4G, Wi-Fi","1 GB RAM, 8 GB inbuilt",1470 mAh Battery,"2.8 inches, 240 x 320 px Display",2 MP Rear Camera,Memory Card Supported,Bluetooth,NaN
882,Nokia 5710 XpressAudio,4799,NaN,"Dual Sim, 3G, 4G",No Wifi,Unisoc T107,"48 MB RAM, 128 MB inbuilt",1450 mAh Battery,"2.4 inches, 240 x 320 px Display",0.3 MP Rear Camera,"Memory Card Supported, upto 32 GB"
913,Apple iPhone 12 Mini (256GB),55999,75.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Bionic A14, Hexa Core, 3.1 GHz Processor","4 GB RAM, 256 GB inbuilt","5.4 inches, 1080 x 2340 px Display",12 MP + 12 MP Dual Rear & 12 MP Front Camera,Memory Card Not Supported,iOS v14,No FM Radio
914,Apple iPhone 12 (256GB),67999,76.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Bionic A14, Hexa Core, 3.1 GHz Processor","4 GB RAM, 256 GB inbuilt","6.1 inches, 1170 x 2532 px Display with Large ...",12 MP + 12 MP Dual Rear & 12 MP Front Camera,Memory Card Not Supported,iOS v14,No FM Radio
925,Nokia 3310 4G,3999,NaN,"Dual Sim, 3G, 4G, VoLTE, Wi-Fi","256 MB RAM, 512 MB inbuilt",1200 mAh Battery,"2.4 inches, 240 x 320 px Display",2 MP Rear Camera,"Memory Card Supported, upto 32 GB",Bluetooth,Browser
927,Samsung Guru E1200,1685,NaN,Single Sim,No Wifi,800 mAh Battery,"1.5 inches, 128 x 128 px Display",No Rear Camera,No FM Radio,NaN,NaN
930,iKall K88 Pro 4G,2099,NaN,"Dual Sim, 3G, 4G, VoLTE","48 MB RAM, 128 MB inbuilt",1800 mAh Battery,"2.4 inches, 240 x 360 px Display",0.3 MP Rear Camera,"Memory Card Supported, upto 128 GB",Bluetooth,Browser
988,Nokia 5310 Dual Sim,3399,NaN,Dual Sim,"8 MB RAM, 16 MB inbuilt",1200 mAh Battery,"2.4 inches, 240 x 320 px Display",0.3 MP Rear Camera,"Memory Card Supported, upto 32 GB",Bluetooth,Browser
1000,XTouch F40 Flip,1999,NaN,Dual Sim,No 3G,No Wifi,"32 MB RAM, 32 MB inbuilt",800 mAh Battery,"1.77 inches, 240 x 320 px Display",Dual Display,1.3 MP Rear Camera

In [121]:
df["camera"] = df["camera"].fillna(0)

In [122]:
for i in df.index:
    if "Camera" not in df["camera"][i]:
        print("i" , df["camera"][i])

i Foldable Display, Dual Display
i Foldable Display
i Memory Card Not Supported
i Memory Card Not Supported
i Dual Display
i Foldable Display, Dual Display
i Foldable Display, Dual Display
i Dual Display
i Foldable Display, Dual Display
i Memory Card Not Supported
i Foldable Display, Dual Display
i Foldable Display, Dual Display
i Memory Card Not Supported
i Foldable Display, Dual Display
i 2.8 inches, 240 x 320 px Display
i Foldable Display, Dual Display
i Memory Card Not Supported
i Memory Card Not Supported
i Foldable Display, Dual Display
i Foldable Display, Dual Display
i 2.4 inches, 240 x 320 px Display
i Foldable Display, Dual Display
i Dual Display
i 2.8 inches, 240 x 320 px Display
i Android v5.0 (Lollipop)
i 1.8 inches, 128 x 160 px Display
i Dual Display
i Memory Card Not Supported
i Memory Card Supported, upto 32 GB
i Kaios v3.0
i Memory Card Supported, upto 32 GB
i No FM Radio
i Memory Card Supported, upto 32 GB
i Dual Display

TypeError: argument of type 'int' is not iterable

In [123]:
df["camera"].isnull().sum()

np.int64(0)

In [124]:
df[~df["camera"].str.contains("Camera" , na = False)].index

Index([  69,   98,  111,  149,  155,  159,  236,  271,  306,  307,  321,  322,
        363,  365,  376,  392,  439,  448,  482,  504,  551,  569,  570,  582,
        608,  611,  613,  628,  640,  645,  647,  657,  665,  682,  699,  703,
        709,  721,  726,  748,  754,  757,  762,  790,  817,  844,  853,  857,
        881,  882,  894,  913,  914,  925,  927,  930,  943,  954,  988,  993,
       1000, 1014],
      dtype='int64')

In [125]:
df

,model,price,rating,sim,processor,ram,battery,display,camera,card,os
0,OnePlus 11 5G,54999,89.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 8 Gen2, Octa Core, 3.2 GHz Processor","12 GB RAM, 256 GB inbuilt",5000 mAh Battery with 100W Fast Charging,"6.7 inches, 1440 x 3216 px, 120 Hz Display wit...",50 MP + 48 MP + 32 MP Triple Rear & 16 MP Fron...,Memory Card Not Supported,Android v13
1,OnePlus Nord CE 2 Lite 5G,19989,81.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi","Snapdragon 695, Octa Core, 2.2 GHz Processor","6 GB RAM, 128 GB inbuilt",5000 mAh Battery with 33W Fast Charging,"6.59 inches, 1080 x 2412 px, 120 Hz Display wi...",64 MP + 2 MP + 2 MP Triple Rear & 16 MP Front ...,"Memory Card (Hybrid), upto 1 TB",Android v12
2,Samsung Galaxy A14 5G,16499,75.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi","Exynos 1330, Octa Core, 2.4 GHz Processor","4 GB RAM, 64 GB inbuilt",5000 mAh Battery with 15W Fast Charging,"6.6 inches, 1080 x 2408 px, 90 Hz Display with...",50 MP + 2 MP + 2 MP Triple Rear & 13 MP Front ...,"Memory Card Supported, upto 1 TB",Android v13
3,Motorola Moto G62 5G,14999,81.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi","Snapdragon 695, Octa Core, 2.2 GHz Processor","6 GB RAM, 128 GB inbuilt",5000 mAh Battery with Fast Charging,"6.55 inches, 1080 x 2400 px, 120 Hz Display wi...",50 MP + 8 MP + 2 MP Triple Rear & 16 MP Front ...,"Memory Card (Hybrid), upto 1 TB",Android v12
4,Realme 10 Pro Plus,24999,82.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi","Dimensity 1080, Octa Core, 2.6 GHz Processor","6 GB RAM, 128 GB inbuilt",5000 mAh Battery with 67W Fast Charging,"6.7 inches, 1080 x 2412 px, 120 Hz Display wit...",108 MP + 8 MP + 2 MP Triple Rear & 16 MP Front...,Memory Card Not Supported,Android v13
...,...,...,...,...,...,...,...,...,...,...,...
1015,Motorola Moto Edge S30 Pro,34990,83.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi","Snapdragon 8 Gen1, Octa Core, 3 GHz Processor","8 GB RAM, 128 GB inbuilt",5000 mAh Battery with 68.2W Fast Charging,"6.67 inches, 1080 x 2460 px, 120 Hz Display wi...",64 MP + 8 MP + 2 MP Triple Rear & 16 MP Front ...,Android v12,No FM Radio
1016,Honor X8 5G,14990,75.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi","Snapdragon 480+, Octa Core, 2.2 GHz Processor","6 GB RAM, 128 GB inbuilt",5000 mAh Battery with 22.5W Fast Charging,"6.5 inches, 720 x 1600 px Display with Water D...",48 MP + 2 MP + Depth Sensor Triple Rear & 8 MP...,"Memory Card Supported, upto 1 TB",Android v11
1017,POCO X4 GT 5G (8GB RAM + 256GB),28990,85.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC, IR Bl...","Dimensity 8100, Octa Core, 2.85 GHz Processor","8 GB RAM, 256 GB inbuilt",5080 mAh Battery with 67W Fast Charging,"6.6 inches, 1080 x 2460 px, 144 Hz Display wit...",64 MP + 8 MP + 2 MP Triple Rear & 16 MP Front ...,Memory Card Not Supported,Android v12
1018,Motorola Moto G91 5G,19990,80.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 695, Octa Core, 2.2 GHz Processor","6 GB RAM, 128 GB inbuilt",5000 mAh Battery with Fast Charging,"6.8 inches, 1080 x 2400 px Display with Punch ...",108 MP + 8 MP + 2 MP Triple Rear & 32 MP Front...,"Memory Card Supported, upto 1 TB",Android v12
1019,Samsung Galaxy M52s 5G,24990,74.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi",Octa Core Processor,"8 GB RAM, 128 GB inbuilt",5000 mAh Battery with Fast Charging,"6.5 inches, 1080 x 2400 px Display with Water ...",64 MP + 8 MP + 5 MP Triple Rear & 32 MP Front ...,"Memory Card Supported, upto 1 TB",Android v12

In [126]:
df.head()

,model,price,rating,sim,processor,ram,battery,display,camera,card,os
0,OnePlus 11 5G,54999,89.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 8 Gen2, Octa Core, 3.2 GHz Processor","12 GB RAM, 256 GB inbuilt",5000 mAh Battery with 100W Fast Charging,"6.7 inches, 1440 x 3216 px, 120 Hz Display wit...",50 MP + 48 MP + 32 MP Triple Rear & 16 MP Fron...,Memory Card Not Supported,Android v13
1,OnePlus Nord CE 2 Lite 5G,19989,81.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi","Snapdragon 695, Octa Core, 2.2 GHz Processor","6 GB RAM, 128 GB inbuilt",5000 mAh Battery with 33W Fast Charging,"6.59 inches, 1080 x 2412 px, 120 Hz Display wi...",64 MP + 2 MP + 2 MP Triple Rear & 16 MP Front ...,"Memory Card (Hybrid), upto 1 TB",Android v12
2,Samsung Galaxy A14 5G,16499,75.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi","Exynos 1330, Octa Core, 2.4 GHz Processor","4 GB RAM, 64 GB inbuilt",5000 mAh Battery with 15W Fast Charging,"6.6 inches, 1080 x 2408 px, 90 Hz Display with...",50 MP + 2 MP + 2 MP Triple Rear & 13 MP Front ...,"Memory Card Supported, upto 1 TB",Android v13
3,Motorola Moto G62 5G,14999,81.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi","Snapdragon 695, Octa Core, 2.2 GHz Processor","6 GB RAM, 128 GB inbuilt",5000 mAh Battery with Fast Charging,"6.55 inches, 1080 x 2400 px, 120 Hz Display wi...",50 MP + 8 MP + 2 MP Triple Rear & 16 MP Front ...,"Memory Card (Hybrid), upto 1 TB",Android v12
4,Realme 10 Pro Plus,24999,82.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi","Dimensity 1080, Octa Core, 2.6 GHz Processor","6 GB RAM, 128 GB inbuilt",5000 mAh Battery with 67W Fast Charging,"6.7 inches, 1080 x 2412 px, 120 Hz Display wit...",108 MP + 8 MP + 2 MP Triple Rear & 16 MP Front...,Memory Card Not Supported,Android v13

In [127]:
for i in  df.index:
    if "Card" not in df["card"][i]:
        print(i , df["card"][i])

8 Android v12
9 Android v12
12 Android v12
17 Android v13
18 Android v12
20 Android v13
21 Android v12
24 Android v13
29 Android v13
37 Android v12
39 Android v13
51 Android v13
58 Android v13
60 Android v12
61 Android v13
65 Android v13
66 Android v12
69 64 MP + 10 MP + 8 MP Triple Rear & 32 MP Front Camera
73 Android v12
85 Android v12
91 Android v12
93 Android v13
97 Android v13
98 50 MP Quad Rear & 16 MP Front Camera
102 Android v12
106 Android v13
107 Android v12
109 Android v12
110 Android v12
111 iOS v14
112 Android v12
115 Android v12
119 Android v13
120 Android v12
121 Android v12
133 Android v12
139 Android v12
141 Android v13
146 Android v11
149 iOS v14
155 5 MP Rear Camera
159 50 MP + 48 MP + 32 MP Triple Rear & 32 MP + 32 MP Dual Front Camera
163 Android v13
168 Android v12
170 Android v11
183 Android v13
186 Android v11
189 Android v11
196 Android v12
202 Android v12
203 Android v12
206 Android v12
209 Android v12
211 Android v12
215 Android v12
216 Android v13
220 Android v13
223 Android v12
228 Android v12
229 Android v12
230 Android v12
231 Android v13
236 50 MP + 13 MP + 8 MP Triple Rear & 20 MP Front Camera
244 Android v13
249 Android v13
251 Android v12
257 Android v12
258 Android v11
267 Android v13
269 Android v13
271 2 MP Rear Camera
272 Android v12
276 Android v12
286 Android v12
296 Android v12
298 Android v13
301 Android v12
306 12 MP + 12 MP Dual Rear & 10 MP Front Camera
307 iOS v14
308 Android v12
311 Android v11
313 Android v12
319 Android v11
320 Android v13
321 50 MP + 12 MP + 10 MP Triple Rear & 10 MP + 4 MP Dual Front Camera
322 64 MP + 16 MP + 8 MP Triple Rear & 32 MP Front Camera
326 Android v12
328 Android v10
335 Android v12
342 Android v12
347 Android v13
354 Android v13
359 Android v12
361 Android v12
362 Android v12
363 iOS v14
365 50 MP + 8 MP Dual Rear & 32 MP Front Camera
366 Android v12
371 Android v11
376 Dual Display
379 Android v12
380 Android v10
383 Android v11
392 50 MP + 8 MP Dual Rear & 32 MP Front Camera
399 Android v9.0 (Pie)
401 Android v13
415 Android v11
422 Android v12
423 Android v12
424 Android v12
425 Android v12.1
428 Android v11
434 Android v12
439 iOS v15
448 iOS v15
453 Android v11
456 Android v12
458 Android v12
463 Android v13
464 Android v13
482 50 MP Quad Rear & 16 MP + 16 MP Dual Front Camera
493 Android v12
495 Android v12
500 Android v11
504 12 MP + 12 MP Dual Rear & 10 MP Front Camera
508 Android v12
515 Android v11
516 Android v13
519 Android v12
525 Android v11
526 Android v12
534 Android v12
535 Android v12
540 Android v12
541 Android v12
544 Android v12
545 Android v12
551 1.3 MP Rear Camera
554 Android v11
557 Android v12
559 Android v12
561 Android v13
565 Android v11
566 Android v11
568 Android v13
569 12 MP + 12 MP + 12 MP Triple Rear & 10 MP + 4 MP Dual Front Camera
570 64 MP + 13 MP + 12 MP Triple Rear & 32 MP Front Camera

TypeError: argument of type 'float' is not iterable

In [128]:
df["card"].index

RangeIndex(start=0, stop=1020, step=1)

In [129]:
df[~df["card"].str.contains("Card" , na = False)].index

Index([   8,    9,   12,   17,   18,   20,   21,   24,   29,   37,
       ...
        993, 1000, 1007, 1008, 1009, 1011, 1012, 1013, 1014, 1015],
      dtype='int64', length=279)

In [130]:
df.head()

,model,price,rating,sim,processor,ram,battery,display,camera,card,os
0,OnePlus 11 5G,54999,89.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 8 Gen2, Octa Core, 3.2 GHz Processor","12 GB RAM, 256 GB inbuilt",5000 mAh Battery with 100W Fast Charging,"6.7 inches, 1440 x 3216 px, 120 Hz Display wit...",50 MP + 48 MP + 32 MP Triple Rear & 16 MP Fron...,Memory Card Not Supported,Android v13
1,OnePlus Nord CE 2 Lite 5G,19989,81.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi","Snapdragon 695, Octa Core, 2.2 GHz Processor","6 GB RAM, 128 GB inbuilt",5000 mAh Battery with 33W Fast Charging,"6.59 inches, 1080 x 2412 px, 120 Hz Display wi...",64 MP + 2 MP + 2 MP Triple Rear & 16 MP Front ...,"Memory Card (Hybrid), upto 1 TB",Android v12
2,Samsung Galaxy A14 5G,16499,75.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi","Exynos 1330, Octa Core, 2.4 GHz Processor","4 GB RAM, 64 GB inbuilt",5000 mAh Battery with 15W Fast Charging,"6.6 inches, 1080 x 2408 px, 90 Hz Display with...",50 MP + 2 MP + 2 MP Triple Rear & 13 MP Front ...,"Memory Card Supported, upto 1 TB",Android v13
3,Motorola Moto G62 5G,14999,81.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi","Snapdragon 695, Octa Core, 2.2 GHz Processor","6 GB RAM, 128 GB inbuilt",5000 mAh Battery with Fast Charging,"6.55 inches, 1080 x 2400 px, 120 Hz Display wi...",50 MP + 8 MP + 2 MP Triple Rear & 16 MP Front ...,"Memory Card (Hybrid), upto 1 TB",Android v12
4,Realme 10 Pro Plus,24999,82.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi","Dimensity 1080, Octa Core, 2.6 GHz Processor","6 GB RAM, 128 GB inbuilt",5000 mAh Battery with 67W Fast Charging,"6.7 inches, 1080 x 2412 px, 120 Hz Display wit...",108 MP + 8 MP + 2 MP Triple Rear & 16 MP Front...,Memory Card Not Supported,Android v13

In [131]:
df.unstack()

model  0                   OnePlus 11 5G
       1       OnePlus Nord CE 2 Lite 5G
       2           Samsung Galaxy A14 5G
       3            Motorola Moto G62 5G
       4              Realme 10 Pro Plus
                         ...
os     1015                  No FM Radio
       1016                  Android v11
       1017                  Android v12
       1018                  Android v12
       1019                  Android v12
Length: 11220, dtype: object

In [83]:
df.head()

,index,model,price,rating,sim,processor,ram,battery,display,camera,card,os
0,2,OnePlus 11 5G,54999,89.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 8 Gen2, Octa Core, 3.2 GHz Processor","12 GB RAM, 256 GB inbuilt",5000 mAh Battery with 100W Fast Charging,"6.7 inches, 1440 x 3216 px, 120 Hz Display wit...",50 MP + 48 MP + 32 MP Triple Rear & 16 MP Fron...,Memory Card Not Supported,Android v13
1,3,OnePlus Nord CE 2 Lite 5G,19989,81.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi","Snapdragon 695, Octa Core, 2.2 GHz Processor","6 GB RAM, 128 GB inbuilt",5000 mAh Battery with 33W Fast Charging,"6.59 inches, 1080 x 2412 px, 120 Hz Display wi...",64 MP + 2 MP + 2 MP Triple Rear & 16 MP Front ...,"Memory Card (Hybrid), upto 1 TB",Android v12
2,4,Samsung Galaxy A14 5G,16499,75.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi","Exynos 1330, Octa Core, 2.4 GHz Processor","4 GB RAM, 64 GB inbuilt",5000 mAh Battery with 15W Fast Charging,"6.6 inches, 1080 x 2408 px, 90 Hz Display with...",50 MP + 2 MP + 2 MP Triple Rear & 13 MP Front ...,"Memory Card Supported, upto 1 TB",Android v13
3,5,Motorola Moto G62 5G,14999,81.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi","Snapdragon 695, Octa Core, 2.2 GHz Processor","6 GB RAM, 128 GB inbuilt",5000 mAh Battery with Fast Charging,"6.55 inches, 1080 x 2400 px, 120 Hz Display wi...",50 MP + 8 MP + 2 MP Triple Rear & 16 MP Front ...,"Memory Card (Hybrid), upto 1 TB",Android v12
4,6,Realme 10 Pro Plus,24999,82.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi","Dimensity 1080, Octa Core, 2.6 GHz Processor","6 GB RAM, 128 GB inbuilt",5000 mAh Battery with 67W Fast Charging,"6.7 inches, 1080 x 2412 px, 120 Hz Display wit...",108 MP + 8 MP + 2 MP Triple Rear & 16 MP Front...,Memory Card Not Supported,Android v13

In [132]:
df = df[df["price"]>5000]

In [133]:
df

,model,price,rating,sim,processor,ram,battery,display,camera,card,os
0,OnePlus 11 5G,54999,89.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 8 Gen2, Octa Core, 3.2 GHz Processor","12 GB RAM, 256 GB inbuilt",5000 mAh Battery with 100W Fast Charging,"6.7 inches, 1440 x 3216 px, 120 Hz Display wit...",50 MP + 48 MP + 32 MP Triple Rear & 16 MP Fron...,Memory Card Not Supported,Android v13
1,OnePlus Nord CE 2 Lite 5G,19989,81.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi","Snapdragon 695, Octa Core, 2.2 GHz Processor","6 GB RAM, 128 GB inbuilt",5000 mAh Battery with 33W Fast Charging,"6.59 inches, 1080 x 2412 px, 120 Hz Display wi...",64 MP + 2 MP + 2 MP Triple Rear & 16 MP Front ...,"Memory Card (Hybrid), upto 1 TB",Android v12
2,Samsung Galaxy A14 5G,16499,75.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi","Exynos 1330, Octa Core, 2.4 GHz Processor","4 GB RAM, 64 GB inbuilt",5000 mAh Battery with 15W Fast Charging,"6.6 inches, 1080 x 2408 px, 90 Hz Display with...",50 MP + 2 MP + 2 MP Triple Rear & 13 MP Front ...,"Memory Card Supported, upto 1 TB",Android v13
3,Motorola Moto G62 5G,14999,81.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi","Snapdragon 695, Octa Core, 2.2 GHz Processor","6 GB RAM, 128 GB inbuilt",5000 mAh Battery with Fast Charging,"6.55 inches, 1080 x 2400 px, 120 Hz Display wi...",50 MP + 8 MP + 2 MP Triple Rear & 16 MP Front ...,"Memory Card (Hybrid), upto 1 TB",Android v12
4,Realme 10 Pro Plus,24999,82.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi","Dimensity 1080, Octa Core, 2.6 GHz Processor","6 GB RAM, 128 GB inbuilt",5000 mAh Battery with 67W Fast Charging,"6.7 inches, 1080 x 2412 px, 120 Hz Display wit...",108 MP + 8 MP + 2 MP Triple Rear & 16 MP Front...,Memory Card Not Supported,Android v13
...,...,...,...,...,...,...,...,...,...,...,...
1015,Motorola Moto Edge S30 Pro,34990,83.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi","Snapdragon 8 Gen1, Octa Core, 3 GHz Processor","8 GB RAM, 128 GB inbuilt",5000 mAh Battery with 68.2W Fast Charging,"6.67 inches, 1080 x 2460 px, 120 Hz Display wi...",64 MP + 8 MP + 2 MP Triple Rear & 16 MP Front ...,Android v12,No FM Radio
1016,Honor X8 5G,14990,75.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi","Snapdragon 480+, Octa Core, 2.2 GHz Processor","6 GB RAM, 128 GB inbuilt",5000 mAh Battery with 22.5W Fast Charging,"6.5 inches, 720 x 1600 px Display with Water D...",48 MP + 2 MP + Depth Sensor Triple Rear & 8 MP...,"Memory Card Supported, upto 1 TB",Android v11
1017,POCO X4 GT 5G (8GB RAM + 256GB),28990,85.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC, IR Bl...","Dimensity 8100, Octa Core, 2.85 GHz Processor","8 GB RAM, 256 GB inbuilt",5080 mAh Battery with 67W Fast Charging,"6.6 inches, 1080 x 2460 px, 144 Hz Display wit...",64 MP + 8 MP + 2 MP Triple Rear & 16 MP Front ...,Memory Card Not Supported,Android v12
1018,Motorola Moto G91 5G,19990,80.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 695, Octa Core, 2.2 GHz Processor","6 GB RAM, 128 GB inbuilt",5000 mAh Battery with Fast Charging,"6.8 inches, 1080 x 2400 px Display with Punch ...",108 MP + 8 MP + 2 MP Triple Rear & 32 MP Front...,"Memory Card Supported, upto 1 TB",Android v12
1019,Samsung Galaxy M52s 5G,24990,74.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi",Octa Core Processor,"8 GB RAM, 128 GB inbuilt",5000 mAh Battery with Fast Charging,"6.5 inches, 1080 x 2400 px Display with Water ...",64 MP + 8 MP + 5 MP Triple Rear & 32 MP Front ...,"Memory Card Supported, upto 1 TB",Android v12

In [134]:
df.head()

,model,price,rating,sim,processor,ram,battery,display,camera,card,os
0,OnePlus 11 5G,54999,89.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 8 Gen2, Octa Core, 3.2 GHz Processor","12 GB RAM, 256 GB inbuilt",5000 mAh Battery with 100W Fast Charging,"6.7 inches, 1440 x 3216 px, 120 Hz Display wit...",50 MP + 48 MP + 32 MP Triple Rear & 16 MP Fron...,Memory Card Not Supported,Android v13
1,OnePlus Nord CE 2 Lite 5G,19989,81.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi","Snapdragon 695, Octa Core, 2.2 GHz Processor","6 GB RAM, 128 GB inbuilt",5000 mAh Battery with 33W Fast Charging,"6.59 inches, 1080 x 2412 px, 120 Hz Display wi...",64 MP + 2 MP + 2 MP Triple Rear & 16 MP Front ...,"Memory Card (Hybrid), upto 1 TB",Android v12
2,Samsung Galaxy A14 5G,16499,75.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi","Exynos 1330, Octa Core, 2.4 GHz Processor","4 GB RAM, 64 GB inbuilt",5000 mAh Battery with 15W Fast Charging,"6.6 inches, 1080 x 2408 px, 90 Hz Display with...",50 MP + 2 MP + 2 MP Triple Rear & 13 MP Front ...,"Memory Card Supported, upto 1 TB",Android v13
3,Motorola Moto G62 5G,14999,81.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi","Snapdragon 695, Octa Core, 2.2 GHz Processor","6 GB RAM, 128 GB inbuilt",5000 mAh Battery with Fast Charging,"6.55 inches, 1080 x 2400 px, 120 Hz Display wi...",50 MP + 8 MP + 2 MP Triple Rear & 16 MP Front ...,"Memory Card (Hybrid), upto 1 TB",Android v12
4,Realme 10 Pro Plus,24999,82.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi","Dimensity 1080, Octa Core, 2.6 GHz Processor","6 GB RAM, 128 GB inbuilt",5000 mAh Battery with 67W Fast Charging,"6.7 inches, 1080 x 2412 px, 120 Hz Display wit...",108 MP + 8 MP + 2 MP Triple Rear & 16 MP Front...,Memory Card Not Supported,Android v13

In [135]:
processor_rows = set((642,647,649,659,667,701,750,759,819,859,883,884,919,927,929,932,1002))
ram_rows = set((441,485,534,553,584,610,613,642,647,649,659,667,701,750,759,819,859,884,919,927,929,932,990,1002))
battery_rows = set((113,151,309,365,378,441,450,553,584,610,613,630,642,647,649,659,667,701,750,756,759,764,819,855,859,884,915,916,927,929,932,990,1002))
display_rows = set((378,441,450,553,584,610,613,630,642,647,649,659,667,701,750,759,764,819,859,884,915,916,927,929,932,990,1002))
camera_rows = set((100,113,151,157,161,238,273,308,309,323,324,365,367,378,394,441,450,484,506,534,553,571,572,575,584,610,613,615,630,642,647,649,659,667,684,687,705,711,723,728,750,756,759,764,792,819,846,854,855,858,883,884,896,915,916,927,929,932,945,956,990,995,1002,1016 ))

In [136]:
processor_rows

{642,
 647,
 649,
 659,
 667,
 701,
 750,
 759,
 819,
 859,
 883,
 884,
 919,
 927,
 929,
 932,
 1002}

In [138]:
df = df.reset_index()
df["index"] = df["index"]+2

In [140]:
df[df["index"].isin([4,5,6,7,8])]

,level_0,index,model,price,rating,sim,processor,ram,battery,display,camera,card,os
0,0,4,OnePlus 11 5G,54999,89.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 8 Gen2, Octa Core, 3.2 GHz Processor","12 GB RAM, 256 GB inbuilt",5000 mAh Battery with 100W Fast Charging,"6.7 inches, 1440 x 3216 px, 120 Hz Display wit...",50 MP + 48 MP + 32 MP Triple Rear & 16 MP Fron...,Memory Card Not Supported,Android v13
1,1,5,OnePlus Nord CE 2 Lite 5G,19989,81.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi","Snapdragon 695, Octa Core, 2.2 GHz Processor","6 GB RAM, 128 GB inbuilt",5000 mAh Battery with 33W Fast Charging,"6.59 inches, 1080 x 2412 px, 120 Hz Display wi...",64 MP + 2 MP + 2 MP Triple Rear & 16 MP Front ...,"Memory Card (Hybrid), upto 1 TB",Android v12
2,2,6,Samsung Galaxy A14 5G,16499,75.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi","Exynos 1330, Octa Core, 2.4 GHz Processor","4 GB RAM, 64 GB inbuilt",5000 mAh Battery with 15W Fast Charging,"6.6 inches, 1080 x 2408 px, 90 Hz Display with...",50 MP + 2 MP + 2 MP Triple Rear & 13 MP Front ...,"Memory Card Supported, upto 1 TB",Android v13
3,3,7,Motorola Moto G62 5G,14999,81.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi","Snapdragon 695, Octa Core, 2.2 GHz Processor","6 GB RAM, 128 GB inbuilt",5000 mAh Battery with Fast Charging,"6.55 inches, 1080 x 2400 px, 120 Hz Display wi...",50 MP + 8 MP + 2 MP Triple Rear & 16 MP Front ...,"Memory Card (Hybrid), upto 1 TB",Android v12
4,4,8,Realme 10 Pro Plus,24999,82.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi","Dimensity 1080, Octa Core, 2.6 GHz Processor","6 GB RAM, 128 GB inbuilt",5000 mAh Battery with 67W Fast Charging,"6.7 inches, 1080 x 2412 px, 120 Hz Display wit...",108 MP + 8 MP + 2 MP Triple Rear & 16 MP Front...,Memory Card Not Supported,Android v13

In [146]:
df[df["index"].isin(processor_rows| ram_rows | battery_rows|display_rows|camera_rows)]

,level_0,index,model,price,rating,sim,processor,ram,battery,display,camera,card,os
96,96,100,OPPO A17,12499,72.0,"Dual Sim, 3G, 4G, VoLTE, Wi-Fi","Helio G35, Octa Core, 2.3 GHz Processor","4 GB RAM, 64 GB inbuilt",5000 mAh Battery with Fast Charging,"6.56 inches, 720 x 1612 px Display with Water ...",50 MP + 2 MP Dual Rear & 5 MP Front Camera,"Memory Card Supported, upto 1 TB",Android v12
109,109,113,OnePlus 10R 5G (12GB RAM + 256GB),36999,87.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Dimensity 8100 Max, Octa Core, 2.85 GHz Processor","12 GB RAM, 256 GB inbuilt",5000 mAh Battery with 80W Fast Charging,"6.7 inches, 1080 x 2412 px, 120 Hz Display wit...",50 MP + 8 MP + 2 MP Triple Rear & 16 MP Front ...,Android v12,Bluetooth
146,146,151,Samsung Galaxy M34 5G,16999,84.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Exynos 1200, Octa Core, 2.4 GHz Processor","6 GB RAM, 128 GB inbuilt",6000 mAh Battery with 25W Fast Charging,"6.5 inches, 1080 x 2400 px, 120 Hz Display wit...",64 MP Quad Rear & 32 MP Front Camera,Memory Card (Hybrid),Android v12
152,152,157,Oppo A98,30990,87.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 8 Gen1, Octa Core, 3 GHz Processor","8 GB RAM, 128 GB inbuilt",5000 mAh Battery with 67W Fast Charging,"6.7 inches, 1080 x 2412 px, 120 Hz Display wit...",108 MP + 2 MP Dual Rear & 16 MP Front Camera,"Memory Card Supported, upto 1 TB",Android v12
155,155,161,OPPO F21 Pro 5G,25969,82.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi","Snapdragon 695, Octa Core, 2.2 GHz Processor","8 GB RAM, 128 GB inbuilt",4500 mAh Battery with 33W Fast Charging,"6.43 inches, 1080 x 2400 px Display with Punch...",64 MP + 2 MP + 2 MP Triple Rear & 16 MP Front ...,"Memory Card Supported, upto 1 TB",Android v12

In [147]:
df[df["index"].isin(processor_rows& ram_rows & battery_rows&display_rows&camera_rows)]

,level_0,index,model,price,rating,sim,processor,ram,battery,display,camera,card,os
621,621,642,Tecno Camon 19 Pro,17990,81.0,"Dual Sim, 3G, 4G, VoLTE, Wi-Fi","Helio G96, Octa Core, 2.05 GHz Processor","8 GB RAM, 128 GB inbuilt",5000 mAh Battery with 33W Fast Charging,"6.8 inches, 1080 x 2460 px, 120 Hz Display wit...",64 MP + 50 MP + 2 MP Triple Rear & 32 MP Front...,Android v12,Bluetooth
625,625,647,Xiaomi 11T Pro 5G (12GB RAM + 256GB),38999,88.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC, IR Bl...","Snapdragon 888 , Octa Core, 2.84 GHz Processor","12 GB RAM, 256 GB inbuilt",5000 mAh Battery with 120W Fast Charging,"6.67 inches, 1080 x 2400 px, 120 Hz Display wi...",108 MP + 8 MP + 5 MP Triple Rear & 16 MP Front...,Android v11,No FM Radio
627,627,649,Nokia 2760 Flip,5490,NaN,"Dual Sim, 3G, 4G, Wi-Fi",1450 mAh Battery,"3.6 inches, 240 x 320 px Display",5 MP Rear & 5 MP Front Camera,"Memory Card Supported, upto 32 GB",Kaios v3.0,Bluetooth,NaN
636,636,659,Xiaomi Redmi 9,8999,68.0,"Dual Sim, 3G, 4G, VoLTE, Wi-Fi","Helio G35, Octa Core, 2.3 GHz Processor","4 GB RAM, 64 GB inbuilt",5000 mAh Battery,"6.53 inches, 720 x 1600 px Display with Water ...",13 MP + 2 MP Dual Rear & 5 MP Front Camera,"Memory Card Supported, upto 512 GB",Android v10
643,643,667,Infinix Hot 12 Pro,10850,74.0,"Dual Sim, 3G, 4G, VoLTE, Wi-Fi","Tiger T616, Octa Core, 2 GHz Processor","6 GB RAM, 64 GB inbuilt",5000 mAh Battery with 18W Fast Charging,"6.6 inches, 720 x 1612 px, 90 Hz Display with ...",50 MP + Depth Sensor Dual Rear & 8 MP Front Ca...,"Memory Card Supported, upto 256 GB",Android v12
723,723,750,Xiaomi Mi 10T Pro 5G,29999,86.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC, IR Bl...","Snapdragon 865 , Octa Core, 2.84 GHz Processor","8 GB RAM, 128 GB inbuilt",5000 mAh Battery with 33W Fast Charging,"6.67 inches, 1080 x 2400 px, 144 Hz Display wi...",108 MP + 13 MP + 5 MP Triple Rear & 20 MP Fron...,Android v10,No FM Radio
731,731,759,Xiaomi Poco F1 (6GB RAM + 128GB),12999,78.0,"Dual Sim, 3G, 4G, VoLTE, Wi-Fi","Snapdragon 845, Octa Core, 2.8 GHz Processor","6 GB RAM, 128 GB inbuilt",4000 mAh Battery with Fast Charging,"6.18 inches, 1080 x 2246 px Display with Large...",12 MP + 5 MP Dual Rear & 20 MP Front Camera,"Memory Card (Hybrid), upto 256 GB",Android v8.1 (Oreo)
790,790,819,Xiaomi Redmi 13 Prime 5G,17990,79.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, IR Blaster","Snapdragon 4 Gen 1, Octa Core, 2 GHz Processor","6 GB RAM, 128 GB inbuilt",5100 mAh Battery with 18W Fast Charging,"6.73 inches, 1080 x 2408 px, 120 Hz Display wi...",64 MP + 2 MP Dual Rear & 16 MP Front Camera,"Memory Card Supported, upto 1 TB",Android v13
849,849,884,Tecno Pova Neo 2,13990,67.0,"Dual Sim, 3G, 4G, VoLTE, Wi-Fi","Helio G85, Octa Core, 2 GHz Processor","6 GB RAM, 128 GB inbuilt",7000 mAh Battery,"6.82 inches, 720 x 1600 px, 90 Hz Display with...",16 MP + 2 MP Dual Rear & 8 MP Front Camera,"Memory Card Supported, upto 512 GB",Android v12
888,888,927,Realme A1,8999,NaN,"Dual Sim, 3G, 4G, VoLTE, Wi-Fi","Helio P70, Octa Core, 2.1 GHz Processor","2 GB RAM, 16 GB inbuilt",4000 mAh Battery,"6.2 inches, 720 x 1520 px Display with Water D...",13 MP + 2 MP Dual Rear & 8 MP Front Camera,"Memory Card Supported, upto 256 GB",Android v8.1 (Oreo)
890,890,932,Apple iPhone 15 Plus,84990,75.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Vo5G, Wi-Fi, NFC","Bionic A16, Hexa Core Processor","8 GB RAM, 128 GB inbuilt",4532 mAh Battery with Fast Charging,"6.71 inches, 1284 x 2778 px, 120 Hz Display wi...",12 MP + 12 MP Dual Rear & 12 MP Front Camera,Memory Card Not Supported,iOS v16
957,957,1002,Blackview BV5200 Pro,8990,67.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Helio G35, Octa Core, 2.3 GHz Processor","4 GB RAM, 64 GB inbuilt",5180 mAh Battery with 10W Fast Charging,"6.1 inches, 720 x 1560 px Display with Punch Hole",13 MP Dual Rear & 8 MP Front Camera,Memory Card Supported,Android v12

In [149]:
df[df["index"].isin(processor_rows)]

,level_0,index,model,price,rating,sim,processor,ram,battery,display,camera,card,os
621,621,642,Tecno Camon 19 Pro,17990,81.0,"Dual Sim, 3G, 4G, VoLTE, Wi-Fi","Helio G96, Octa Core, 2.05 GHz Processor","8 GB RAM, 128 GB inbuilt",5000 mAh Battery with 33W Fast Charging,"6.8 inches, 1080 x 2460 px, 120 Hz Display wit...",64 MP + 50 MP + 2 MP Triple Rear & 32 MP Front...,Android v12,Bluetooth
625,625,647,Xiaomi 11T Pro 5G (12GB RAM + 256GB),38999,88.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC, IR Bl...","Snapdragon 888 , Octa Core, 2.84 GHz Processor","12 GB RAM, 256 GB inbuilt",5000 mAh Battery with 120W Fast Charging,"6.67 inches, 1080 x 2400 px, 120 Hz Display wi...",108 MP + 8 MP + 5 MP Triple Rear & 16 MP Front...,Android v11,No FM Radio
627,627,649,Nokia 2760 Flip,5490,NaN,"Dual Sim, 3G, 4G, Wi-Fi",1450 mAh Battery,"3.6 inches, 240 x 320 px Display",5 MP Rear & 5 MP Front Camera,"Memory Card Supported, upto 32 GB",Kaios v3.0,Bluetooth,NaN
636,636,659,Xiaomi Redmi 9,8999,68.0,"Dual Sim, 3G, 4G, VoLTE, Wi-Fi","Helio G35, Octa Core, 2.3 GHz Processor","4 GB RAM, 64 GB inbuilt",5000 mAh Battery,"6.53 inches, 720 x 1600 px Display with Water ...",13 MP + 2 MP Dual Rear & 5 MP Front Camera,"Memory Card Supported, upto 512 GB",Android v10
643,643,667,Infinix Hot 12 Pro,10850,74.0,"Dual Sim, 3G, 4G, VoLTE, Wi-Fi","Tiger T616, Octa Core, 2 GHz Processor","6 GB RAM, 64 GB inbuilt",5000 mAh Battery with 18W Fast Charging,"6.6 inches, 720 x 1612 px, 90 Hz Display with ...",50 MP + Depth Sensor Dual Rear & 8 MP Front Ca...,"Memory Card Supported, upto 256 GB",Android v12
675,675,701,Infinix Smart 6 Plus,8299,63.0,"Dual Sim, 3G, 4G, VoLTE, Wi-Fi","Helio G25, Octa Core, 2 GHz Processor","3 GB RAM, 64 GB inbuilt",5000 mAh Battery,"6.82 inches, 720 x 1600 px Display with Water ...",8 MP + Depth Sensor Dual Rear & 5 MP Front Camera,"Memory Card Supported, upto 512 GB",Android v12
723,723,750,Xiaomi Mi 10T Pro 5G,29999,86.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC, IR Bl...","Snapdragon 865 , Octa Core, 2.84 GHz Processor","8 GB RAM, 128 GB inbuilt",5000 mAh Battery with 33W Fast Charging,"6.67 inches, 1080 x 2400 px, 144 Hz Display wi...",108 MP + 13 MP + 5 MP Triple Rear & 20 MP Fron...,Android v10,No FM Radio
731,731,759,Xiaomi Poco F1 (6GB RAM + 128GB),12999,78.0,"Dual Sim, 3G, 4G, VoLTE, Wi-Fi","Snapdragon 845, Octa Core, 2.8 GHz Processor","6 GB RAM, 128 GB inbuilt",4000 mAh Battery with Fast Charging,"6.18 inches, 1080 x 2246 px Display with Large...",12 MP + 5 MP Dual Rear & 20 MP Front Camera,"Memory Card (Hybrid), upto 256 GB",Android v8.1 (Oreo)
790,790,819,Xiaomi Redmi 13 Prime 5G,17990,79.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, IR Blaster","Snapdragon 4 Gen 1, Octa Core, 2 GHz Processor","6 GB RAM, 128 GB inbuilt",5100 mAh Battery with 18W Fast Charging,"6.73 inches, 1080 x 2408 px, 120 Hz Display wi...",64 MP + 2 MP Dual Rear & 16 MP Front Camera,"Memory Card Supported, upto 1 TB",Android v13
826,826,859,Realme 6 (6GB RAM + 64GB),12989,77.0,"Dual Sim, 3G, 4G, VoLTE, Wi-Fi","Helio G90T , Octa Core, 2.05 GHz Processor","6 GB RAM, 64 GB inbuilt",4300 mAh Battery with 30W Fast Charging,"6.5 inches, 1080 x 2400 px, 90 Hz Display with...",64 MP Quad Rear & 16 MP Front Camera,"Memory Card Supported, upto 256 GB",Android v10
848,848,883,Nokia X30,41990,85.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 695, Octa Core, 2.2 GHz Processor","6 GB RAM, 128 GB inbuilt",4200 mAh Battery with 33W Fast Charging,"6.43 inches, 1080 x 2400 px, 90 Hz Display wit...",50 MP + 13 MP Dual Rear & 16 MP Front Camera,"Memory Card Supported, upto 1 TB",Android v12
849,849,884,Tecno Pova Neo 2,13990,67.0,"Dual Sim, 3G, 4G, VoLTE, Wi-Fi","Helio G85, Octa Core, 2 GHz Processor","6 GB RAM, 128 GB inbuilt",7000 mAh Battery,"6.82 inches, 720 x 1600 px, 90 Hz Display with...",16 MP + 2 MP Dual Rear & 8 MP Front Camera,"Memory Card Supported, upto 512 GB",Android v12
881,881,919,OPPO A15,9999,66.0,"Dual Sim, 3G, 4G, VoLTE, Wi-Fi","Helio P35, Octa Core, 2.3 GHz Processor","3 GB RAM, 32 GB inbuilt",4230 mAh Battery,"6.52 inches, 720 x 1600 px Display with Water ...",13 MP + 2 MP + 2 MP Triple Rear & 5 MP Front C...,"Memory Card Supported, upto 256 GB",Android v10.0
888,888,927,Realme A1,8999,NaN,"Dual Sim, 3G, 4G, VoLTE, Wi-Fi","Helio P70, Octa Core, 2.1 GHz Processor","2 GB RAM, 16 GB inbuilt",4000 mAh Battery,"6.2 inches, 720 x 1520 px Display with Water D...",13 MP + 2 MP Dual Rear & 8 MP Front Camera,"Memory Card Supported, upto 256 GB",Android v8.1 (Oreo)
890,890,932,Apple iPhone 15 Plus,84990,75.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Vo5G, Wi-Fi, NFC","Bionic A16, Hexa Core Processor","8 GB RAM, 128 GB inbuilt",4532 mAh Battery with Fast Charging,"6.71 inches, 1284 x 2778 px, 120 Hz Display wi...",12 MP + 12 MP Dual Rear & 12 MP Front Camera,Memory Card Not Supported,iOS v16
957,957,1002,Blackview BV5200 Pro,8990,67.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Helio G35, Octa Core, 2.3 GHz Processor","4 GB RAM, 64 GB inbuilt",5180 mAh Battery with 10W Fast Charging,"6.1 inches, 720 x 1560 px Display with Punch Hole",13 MP Dual Rear & 8 MP Front Camera,Memory Card Supported,Android v12

In [150]:
df1.drop([645 , 857 , 882 , 925] , inplace = True)

In [152]:
df[df["index"].isin(processor_rows)]

,level_0,index,model,price,rating,sim,processor,ram,battery,display,camera,card,os
621,621,642,Tecno Camon 19 Pro,17990,81.0,"Dual Sim, 3G, 4G, VoLTE, Wi-Fi","Helio G96, Octa Core, 2.05 GHz Processor","8 GB RAM, 128 GB inbuilt",5000 mAh Battery with 33W Fast Charging,"6.8 inches, 1080 x 2460 px, 120 Hz Display wit...",64 MP + 50 MP + 2 MP Triple Rear & 32 MP Front...,Android v12,Bluetooth
625,625,647,Xiaomi 11T Pro 5G (12GB RAM + 256GB),38999,88.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC, IR Bl...","Snapdragon 888 , Octa Core, 2.84 GHz Processor","12 GB RAM, 256 GB inbuilt",5000 mAh Battery with 120W Fast Charging,"6.67 inches, 1080 x 2400 px, 120 Hz Display wi...",108 MP + 8 MP + 5 MP Triple Rear & 16 MP Front...,Android v11,No FM Radio
627,627,649,Nokia 2760 Flip,5490,NaN,"Dual Sim, 3G, 4G, Wi-Fi",1450 mAh Battery,"3.6 inches, 240 x 320 px Display",5 MP Rear & 5 MP Front Camera,"Memory Card Supported, upto 32 GB",Kaios v3.0,Bluetooth,NaN
636,636,659,Xiaomi Redmi 9,8999,68.0,"Dual Sim, 3G, 4G, VoLTE, Wi-Fi","Helio G35, Octa Core, 2.3 GHz Processor","4 GB RAM, 64 GB inbuilt",5000 mAh Battery,"6.53 inches, 720 x 1600 px Display with Water ...",13 MP + 2 MP Dual Rear & 5 MP Front Camera,"Memory Card Supported, upto 512 GB",Android v10
643,643,667,Infinix Hot 12 Pro,10850,74.0,"Dual Sim, 3G, 4G, VoLTE, Wi-Fi","Tiger T616, Octa Core, 2 GHz Processor","6 GB RAM, 64 GB inbuilt",5000 mAh Battery with 18W Fast Charging,"6.6 inches, 720 x 1612 px, 90 Hz Display with ...",50 MP + Depth Sensor Dual Rear & 8 MP Front Ca...,"Memory Card Supported, upto 256 GB",Android v12
675,675,701,Infinix Smart 6 Plus,8299,63.0,"Dual Sim, 3G, 4G, VoLTE, Wi-Fi","Helio G25, Octa Core, 2 GHz Processor","3 GB RAM, 64 GB inbuilt",5000 mAh Battery,"6.82 inches, 720 x 1600 px Display with Water ...",8 MP + Depth Sensor Dual Rear & 5 MP Front Camera,"Memory Card Supported, upto 512 GB",Android v12
723,723,750,Xiaomi Mi 10T Pro 5G,29999,86.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC, IR Bl...","Snapdragon 865 , Octa Core, 2.84 GHz Processor","8 GB RAM, 128 GB inbuilt",5000 mAh Battery with 33W Fast Charging,"6.67 inches, 1080 x 2400 px, 144 Hz Display wi...",108 MP + 13 MP + 5 MP Triple Rear & 20 MP Fron...,Android v10,No FM Radio
731,731,759,Xiaomi Poco F1 (6GB RAM + 128GB),12999,78.0,"Dual Sim, 3G, 4G, VoLTE, Wi-Fi","Snapdragon 845, Octa Core, 2.8 GHz Processor","6 GB RAM, 128 GB inbuilt",4000 mAh Battery with Fast Charging,"6.18 inches, 1080 x 2246 px Display with Large...",12 MP + 5 MP Dual Rear & 20 MP Front Camera,"Memory Card (Hybrid), upto 256 GB",Android v8.1 (Oreo)
790,790,819,Xiaomi Redmi 13 Prime 5G,17990,79.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, IR Blaster","Snapdragon 4 Gen 1, Octa Core, 2 GHz Processor","6 GB RAM, 128 GB inbuilt",5100 mAh Battery with 18W Fast Charging,"6.73 inches, 1080 x 2408 px, 120 Hz Display wi...",64 MP + 2 MP Dual Rear & 16 MP Front Camera,"Memory Card Supported, upto 1 TB",Android v13
826,826,859,Realme 6 (6GB RAM + 64GB),12989,77.0,"Dual Sim, 3G, 4G, VoLTE, Wi-Fi","Helio G90T , Octa Core, 2.05 GHz Processor","6 GB RAM, 64 GB inbuilt",4300 mAh Battery with 30W Fast Charging,"6.5 inches, 1080 x 2400 px, 90 Hz Display with...",64 MP Quad Rear & 16 MP Front Camera,"Memory Card Supported, upto 256 GB",Android v10
848,848,883,Nokia X30,41990,85.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 695, Octa Core, 2.2 GHz Processor","6 GB RAM, 128 GB inbuilt",4200 mAh Battery with 33W Fast Charging,"6.43 inches, 1080 x 2400 px, 90 Hz Display wit...",50 MP + 13 MP Dual Rear & 16 MP Front Camera,"Memory Card Supported, upto 1 TB",Android v12
849,849,884,Tecno Pova Neo 2,13990,67.0,"Dual Sim, 3G, 4G, VoLTE, Wi-Fi","Helio G85, Octa Core, 2 GHz Processor","6 GB RAM, 128 GB inbuilt",7000 mAh Battery,"6.82 inches, 720 x 1600 px, 90 Hz Display with...",16 MP + 2 MP Dual Rear & 8 MP Front Camera,"Memory Card Supported, upto 512 GB",Android v12
881,881,919,OPPO A15,9999,66.0,"Dual Sim, 3G, 4G, VoLTE, Wi-Fi","Helio P35, Octa Core, 2.3 GHz Processor","3 GB RAM, 32 GB inbuilt",4230 mAh Battery,"6.52 inches, 720 x 1600 px Display with Water ...",13 MP + 2 MP + 2 MP Triple Rear & 5 MP Front C...,"Memory Card Supported, upto 256 GB",Android v10.0
888,888,927,Realme A1,8999,NaN,"Dual Sim, 3G, 4G, VoLTE, Wi-Fi","Helio P70, Octa Core, 2.1 GHz Processor","2 GB RAM, 16 GB inbuilt",4000 mAh Battery,"6.2 inches, 720 x 1520 px Display with Water D...",13 MP + 2 MP Dual Rear & 8 MP Front Camera,"Memory Card Supported, upto 256 GB",Android v8.1 (Oreo)
890,890,932,Apple iPhone 15 Plus,84990,75.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Vo5G, Wi-Fi, NFC","Bionic A16, Hexa Core Processor","8 GB RAM, 128 GB inbuilt",4532 mAh Battery with Fast Charging,"6.71 inches, 1284 x 2778 px, 120 Hz Display wi...",12 MP + 12 MP Dual Rear & 12 MP Front Camera,Memory Card Not Supported,iOS v16
957,957,1002,Blackview BV5200 Pro,8990,67.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Helio G35, Octa Core, 2.3 GHz Processor","4 GB RAM, 64 GB inbuilt",5180 mAh Battery with 10W Fast Charging,"6.1 inches, 720 x 1560 px Display with Punch Hole",13 MP Dual Rear & 8 MP Front Camera,Memory Card Supported,Android v12

In [154]:
df.head()

,level_0,index,model,price,rating,sim,processor,ram,battery,display,camera,card,os
0,0,4,OnePlus 11 5G,54999,89.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 8 Gen2, Octa Core, 3.2 GHz Processor","12 GB RAM, 256 GB inbuilt",5000 mAh Battery with 100W Fast Charging,"6.7 inches, 1440 x 3216 px, 120 Hz Display wit...",50 MP + 48 MP + 32 MP Triple Rear & 16 MP Fron...,Memory Card Not Supported,Android v13
1,1,5,OnePlus Nord CE 2 Lite 5G,19989,81.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi","Snapdragon 695, Octa Core, 2.2 GHz Processor","6 GB RAM, 128 GB inbuilt",5000 mAh Battery with 33W Fast Charging,"6.59 inches, 1080 x 2412 px, 120 Hz Display wi...",64 MP + 2 MP + 2 MP Triple Rear & 16 MP Front ...,"Memory Card (Hybrid), upto 1 TB",Android v12
2,2,6,Samsung Galaxy A14 5G,16499,75.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi","Exynos 1330, Octa Core, 2.4 GHz Processor","4 GB RAM, 64 GB inbuilt",5000 mAh Battery with 15W Fast Charging,"6.6 inches, 1080 x 2408 px, 90 Hz Display with...",50 MP + 2 MP + 2 MP Triple Rear & 13 MP Front ...,"Memory Card Supported, upto 1 TB",Android v13
3,3,7,Motorola Moto G62 5G,14999,81.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi","Snapdragon 695, Octa Core, 2.2 GHz Processor","6 GB RAM, 128 GB inbuilt",5000 mAh Battery with Fast Charging,"6.55 inches, 1080 x 2400 px, 120 Hz Display wi...",50 MP + 8 MP + 2 MP Triple Rear & 16 MP Front ...,"Memory Card (Hybrid), upto 1 TB",Android v12
4,4,8,Realme 10 Pro Plus,24999,82.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi","Dimensity 1080, Octa Core, 2.6 GHz Processor","6 GB RAM, 128 GB inbuilt",5000 mAh Battery with 67W Fast Charging,"6.7 inches, 1080 x 2412 px, 120 Hz Display wit...",108 MP + 8 MP + 2 MP Triple Rear & 16 MP Front...,Memory Card Not Supported,Android v13

In [156]:
df.drop(582 , inplace = True)

In [159]:
temp = df[df["index"].isin(battery_rows)]

In [161]:
temp.index

Index([109, 146, 302, 357, 370, 431, 440, 539, 567, 592, 594, 610, 621, 625,
       627, 636, 643, 675, 723, 728, 731, 735, 790, 823, 826, 849, 877, 878,
       888, 890, 946, 957],
      dtype='int64')

In [163]:
x = temp.iloc[: , 7:].shift(1 , axis = 1).values

In [169]:
df.loc[temp.index,["battery" , "display","camera" , "card" , "os"]]

,battery,display,camera,card,os
109,5000 mAh Battery with 80W Fast Charging,"6.7 inches, 1080 x 2412 px, 120 Hz Display wit...",50 MP + 8 MP + 2 MP Triple Rear & 16 MP Front ...,Android v12,Bluetooth
146,6000 mAh Battery with 25W Fast Charging,"6.5 inches, 1080 x 2400 px, 120 Hz Display wit...",64 MP Quad Rear & 32 MP Front Camera,Memory Card (Hybrid),Android v12
302,4250 mAh Battery with 33W Fast Charging,"6.55 inches, 1080 x 2400 px, 90 Hz Display wit...",64 MP + 8 MP + 5 MP Triple Rear & 20 MP Front ...,Memory Card (Hybrid),Android v11
357,5000 mAh Battery with 120W Fast Charging,"6.67 inches, 1220 x 2712 px, 120 Hz Display wi...",200 MP + 8 MP + 2 MP Triple Rear & 20 MP Front...,Android v12,No FM Radio
370,2800 mAh Battery with Fast Charging,"5.7 inches, 1080 x 2280 px Display",16 MP + 12.2 MP Dual Rear & 8 MP + TOF 3D Dual...,Memory Card Not Supported,Android v10
431,5000 mAh Battery with 10W Fast Charging,"6.5 inches, 720 x 1600 px, 90 Hz Display with ...",50 MP + 2 MP Dual Rear & 8 MP Front Camera,"Memory Card Supported, upto 1 TB",Android v12
440,4980 mAh Battery with 120W Fast Charging,"6.67 inches, 1080 x 2400 px, 120 Hz Display wi...",200 MP + 8 MP + 2 MP Triple Rear & 16 MP Front...,Memory Card Not Supported,Android v12
539,5000 mAh Battery with 33W Fast Charging,"6.5 inches, 1080 x 2400 px, 90 Hz Display with...",64 MP + 2 MP + 2 MP Triple Rear & 16 MP Front ...,"Memory Card Supported, upto 1 TB",Android v11
567,4500 mAh Battery with 20W Fast Charging,"6.58 inches, 1080 x 2400 px, 120 Hz Display wi...",50 MP + 5 MP + 2 MP Triple Rear & 8 MP Front C...,Memory Card (Hybrid),Android v12
592,3500 mAh Battery with 18W Fast Charging,"6.5 inches, 1242 x 2688 px Display with Large ...",12 MP + 12 MP + 12 MP Triple Rear & 12 MP Fron...,Memory Card Not Supported,iOS v13
594,5000 mAh Battery with 33W Fast Charging,"6.5 inches, 1080 x 2400 px, 120 Hz Display",50 MP + 2 MP Dual Rear & 16 MP Front Camera,"Memory Card (Hybrid), upto 1 TB",Android v13
610,4000 mAh Battery with 33W Fast Charging,"6.44 inches, 1080 x 2400 px, 90 Hz Display wit...",64 MP + 8 MP + 2 MP Triple Rear & 44 MP Front ...,Memory Card (Hybrid),Android v11
621,5000 mAh Battery with 33W Fast Charging,"6.8 inches, 1080 x 2460 px, 120 Hz Display wit...",64 MP + 50 MP + 2 MP Triple Rear & 32 MP Front...,Android v12,Bluetooth
625,5000 mAh Battery with 120W Fast Charging,"6.67 inches, 1080 x 2400 px, 120 Hz Display wi...",108 MP + 8 MP + 5 MP Triple Rear & 16 MP Front...,Android v11,No FM Radio
627,5 MP Rear & 5 MP Front Camera,"Memory Card Supported, upto 32 GB",Kaios v3.0,Bluetooth,NaN
636,5000 mAh Battery,"6.53 inches, 720 x 1600 px Display with Water ...",13 MP + 2 MP Dual Rear & 5 MP Front Camera,"Memory Card Supported, upto 512 GB",Android v10
643,5000 mAh Battery with 18W Fast Charging,"6.6 inches, 720 x 1612 px, 90 Hz Display with ...",50 MP + Depth Sensor Dual Rear & 8 MP Front Ca...,"Memory Card Supported, upto 256 GB",Android v12
675,5000 mAh Battery,"6.82 inches, 720 x 1600 px Display with Water ...",8 MP + Depth Sensor Dual Rear & 5 MP Front Camera,"Memory Card Supported, upto 512 GB",Android v12
723,5000 mAh Battery with 33W Fast Charging,"6.67 inches, 1080 x 2400 px, 144 Hz Display wi...",108 MP + 13 MP + 5 MP Triple Rear & 20 MP Fron...,Android v10,No FM Radio
728,4000 mAh Battery with 20W Fast Charging,"6.4 inches, 1080 x 2340 px Display with Water ...",64 MP Quad Rear & 16 MP Front Camera,"Memory Card Supported, upto 256 GB",Android v9.0 (Pie)
731,4000 mAh Battery with Fast Charging,"6.18 inches, 1080 x 2246 px Display with Large...",12 MP + 5 MP Dual Rear & 20 MP Front Camera,"Memory Card (Hybrid), upto 256 GB",Android v8.1 (Oreo)
735,5000 mAh Battery with 120W Fast Charging,"6.67 inches, 1080 x 2400 px, 120 Hz Display wi...",50 MP + 13 MP + 2 MP Triple Rear & 32 MP Front...,Android v13,No FM Radio
790,5100 mAh Battery with 18W Fast Charging,"6.73 inches, 1080 x 2408 px, 120 Hz Display wi...",64 MP + 2 MP Dual Rear & 16 MP Front Camera,"Memory Card Supported, upto 1 TB",Android v13
823,5000 mAh Battery with 18W Fast Charging,"6.5 inches, 720 x 1600 px Display with Water D...",13 MP + 2 MP + 2 MP Triple Rear & 8 MP Front C...,Android v10,No FM Radio
826,4300 mAh Battery with 30W Fast Charging,"6.5 inches, 1080 x 2400 px, 90 Hz Display with...",64 MP Quad Rear & 16 MP Front Camera,"Memory Card Supported, upto 256 GB",Android v10
849,7000 mAh Battery,"6.82 inches, 720 x 1600 px, 90 Hz Display with...",16 MP + 2 MP Dual Rear & 8 MP Front Camera,"Memory Card Supported, upto 512 GB",Android v12
877,6000 mAh Battery with 15W Fast Charging,"6.5 inches, 720 x 1600 px, 90 Hz Display with ...",48 MP Quad Rear & 8 MP Front Camera,"Memory Card Supported, upto 1 TB",Android v11
878,5000 mAh Battery with 18W Fast Charging,"6.52 inches, 720 x 1600 px, 90 Hz Display with...",13 MP + 2 MP + 2 MP Triple Rear & 8 MP Front C...,"Memory Card Supported, upto 256 GB",Android v10
888,4000 mAh Battery,"6.2 inches, 720 x 1520 px Display with Water D...",13 MP + 2 MP Dual Rear & 8 MP Front Camera,"Memory Card Supported, upto 256 GB",Android v8.1 (Oreo)
890,4532 mAh Battery with Fast Charging,"6.71 inches, 1284 x 2778 px, 120 Hz Display wi...",12 MP + 12 MP Dual Rear & 12 MP Front Camera,Memory Card Not Supported,iOS v16
946,5000 mAh Battery,"6.5 inches, 720 x 1544 px Display with Water D...",13 MP + 2 MP Dual Rear & 13 MP Front Camera,"Memory Card Supported, upto 256 GB",Android v10
957,5180 mAh Battery with 10W Fast Charging,"6.1 inches, 720 x 1560 px Display with Punch Hole",13 MP Dual Rear & 8 MP Front Camera,Memory Card Supported,Android v12

In [170]:
df.loc[temp.index,["battery" , "display","camera" , "card" , "os"]] = x

ValueError: Must have equal len keys and value when setting with an ndarray